"""Tripwire for issue #816: PYTHONPATH pointed one level too deep.

Why this file exists: issue #430 established that PYTHONPATH must point at
CPP_DIR (the parent of lib/), never at lib/ itself - `-m lib.X` needs `lib`
importable as a package, so pointing PYTHONPATH at lib/ puts lib's *contents*
on the path instead of lib itself. #430 migrated 13 sites; 57 more carried
the one-level-too-deep form for months because nothing asserted the shape.
The same partial migration left a second, independent defect on many of the
same lines: a bare `python`/`python3` interpreter instead of
`uv run --project "$CPP_DIR" python`, which silently picks up whatever
interpreter is ahead on PATH and can miss pydantic in a fresh checkout
(closed issue #500). This file is the assertion that closes both gaps so a
sweep alone is not mistaken for a fix (#816).

Enumerates by filesystem glob, not `git ls-files` - a new offending file is
caught before it is ever staged. `codex/skills/**` is excluded: it is a
generated mirror of `.claude/commands/**`, regenerated by `make codex-skills`,
never hand-edited - asserting on it would just duplicate this test's real
signal one edit later than it is useful.

Every detector here carries its own synthetic-bad-string control. A regex
that matches nothing (a typo, an escaping slip, an `rglob` pattern that
silently returns no files) passes every real-file assertion below for a
reason that has nothing to do with the code being correct, and that failure
mode looks identical to success. Proving each detector CAN fire, on a fixture
held in this file, is what makes a later false negative unlikely to hide.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]

# A PYTHONPATH value ending in /lib (immediately before a closing quote or a
# `:` component separator) is the #816 depth defect.
DEPTH_DEFECT = re.compile(r'PYTHONPATH="[^"]*/lib(?=[:"])')

# A PYTHONPATH assignment directly chained into a bare python/python3 `-m
# lib.` invocation, with nothing (no `uv run --project ...`) in between, is
# the #816 interpreter defect. Deliberately narrow to `-m lib.` so it does
# not flag unrelated bare-python3 uses elsewhere in these docs (stdlib-only
# `python3 -c "import json..."` helpers, YAML example values for a *target*
# project's own health-check command, prose mentioning python3 in backticks,
# or the intentional `uv run --no-project --with ...` pattern in
# self-improvement/memory.md) - none of those chain directly off a
# `PYTHONPATH="..."` token the way every real #816 site does.
BARE_INTERPRETER = re.compile(r'PYTHONPATH="[^"]*"\s+python3?\s+-m\s+lib\.')


def _markdown_files() -> list[Path]:
    files: list[Path] = []
    for base in (ROOT / ".claude" / "commands", ROOT / ".claude" / "skills"):
        files.extend(sorted(base.rglob("*.md")))
    return files


def test_markdown_file_enumeration_is_non_empty():
    """Guards the silent-pass failure mode of the two tests below: an rglob
    that returns nothing (wrong base dir, wrong extension) would pass every
    per-file assertion for a reason that has nothing to do with correctness."""
    files = _markdown_files()
    assert len(files) > 50, (
        f"expected .claude/commands/**/*.md + .claude/skills/**/*.md to hold "
        f"more than 50 files, found {len(files)} - the enumeration is broken"
    )


def test_depth_detector_can_fire():
    fixture = 'PYTHONPATH="$CPP_DIR/lib:$PYTHONPATH" python3 -m lib.cicd check'
    assert DEPTH_DEFECT.search(fixture), (
        "DEPTH_DEFECT no longer matches the #816 shape it exists to catch"
    )


def test_interpreter_detector_can_fire():
    fixture = 'PYTHONPATH="$CPP_DIR:$PYTHONPATH" python3 -m lib.cicd check'
    assert BARE_INTERPRETER.search(fixture), (
        "BARE_INTERPRETER no longer matches the #816 shape it exists to catch"
    )


@pytest.mark.parametrize("path", _markdown_files(), ids=lambda p: str(p.relative_to(ROOT)))
def test_no_pythonpath_points_at_lib_itself(path: Path):
    text = path.read_text(encoding="utf-8")
    hits = DEPTH_DEFECT.findall(text)
    assert not hits, (
        f"{path.relative_to(ROOT)} has a PYTHONPATH value ending in /lib "
        f"(issue #816): {hits!r}. Point it at the parent of lib/ instead."
    )


@pytest.mark.parametrize("path", _markdown_files(), ids=lambda p: str(p.relative_to(ROOT)))
def test_no_bare_interpreter_invokes_lib(path: Path):
    text = path.read_text(encoding="utf-8")
    hits = [line for line in text.splitlines() if BARE_INTERPRETER.search(line)]
    assert not hits, (
        f"{path.relative_to(ROOT)} invokes `-m lib.` through a bare python "
        f"interpreter instead of `uv run --project ... python` (issue #816): "
        f"{hits!r}"
    )


def test_positive_control_the_correct_form_is_still_present():
    """The correct #430 form must still exist verbatim in its template file -
    if this stops matching, cicd/verify.md was edited or removed."""
    verify_text = (ROOT / ".claude" / "commands" / "cicd" / "verify.md").read_text(encoding="utf-8")
    assert (
        'PYTHONPATH="$CPP_DIR:$PYTHONPATH" uv run --project "$CPP_DIR" python -m lib.cicd verify'
        in verify_text
    )
