"""Regression tests for the global flow-* skill mirror sync/guard (issue #457).

The hazard these pin: the global `~/.claude/skills/flow-*` mirror is the surface
that actually executes when a flow skill is invoked, and it silently drifted from
the `.claude/commands/flow/*` source of truth after #453 rebased the commands onto
native worktrees. `scripts/flow-skill-sync.py` regenerates the mirror and detects
that drift; these tests keep both halves honest.

Hermetic: every test writes into a tmp skills dir and reads the REAL repo command
sources. No git subprocess is spawned, so the tests run in CI's git-less validate
container (see the cpp_validate_container_no_git learning).
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "flow-skill-sync.py"
COMMANDS = ROOT / ".claude" / "commands" / "flow"

_spec = importlib.util.spec_from_file_location("flow_skill_sync", SCRIPT)
assert _spec and _spec.loader
fss = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fss)

EXPECTED_COUNT = len(fss.SKILLS)  # 11 mirrored flow commands


def _write(tmp_skills: Path) -> int:
    return fss.write_mirror(tmp_skills, COMMANDS)


# --------------------------------------------------------------------------- #
# Write + round-trip
# --------------------------------------------------------------------------- #
def test_write_produces_clean_check(tmp_path):
    skills = tmp_path / "skills"
    assert _write(skills) == 0
    written = list(skills.glob("flow-*/SKILL.md"))
    assert len(written) == EXPECTED_COUNT

    findings = fss.classify(skills, COMMANDS)
    assert all(f["status"] == fss.OK for f in findings), findings
    assert fss.drifted(findings) == []


def test_missing_when_not_written(tmp_path):
    skills = tmp_path / "skills"
    skills.mkdir()
    findings = fss.classify(skills, COMMANDS)
    assert len(findings) == EXPECTED_COUNT
    assert all(f["status"] == fss.MISSING for f in findings)
    assert len(fss.drifted(findings)) == EXPECTED_COUNT


def test_idempotent_rewrite(tmp_path):
    skills = tmp_path / "skills"
    _write(skills)
    first = {p: p.read_bytes() for p in skills.glob("flow-*/SKILL.md")}
    _write(skills)
    second = {p: p.read_bytes() for p in skills.glob("flow-*/SKILL.md")}
    assert first == second


# --------------------------------------------------------------------------- #
# Drift detection
# --------------------------------------------------------------------------- #
def test_content_drift_detected(tmp_path):
    skills = tmp_path / "skills"
    _write(skills)

    # Simulate a repo command changing after the mirror was generated by
    # corrupting the recorded source hash on exactly one skill.
    victim = skills / "flow-doctor" / "SKILL.md"
    text = victim.read_text(encoding="utf-8")
    import re

    mutated = re.sub(r"source_sha256: [0-9a-f]{64}", "source_sha256: " + "0" * 64, text)
    assert mutated != text
    victim.write_text(mutated, encoding="utf-8")

    findings = {f["skill"]: f["status"] for f in fss.classify(skills, COMMANDS)}
    assert findings["flow-doctor"] == fss.DRIFTED
    # Everything else stayed in sync.
    assert all(v == fss.OK for k, v in findings.items() if k != "flow-doctor")


def test_untracked_mirror_reads_as_drift(tmp_path):
    """A hand-authored skill with no source_sha256 must register as drift."""
    skills = tmp_path / "skills"
    d = skills / "flow-start"
    d.mkdir(parents=True)
    (d / "SKILL.md").write_text(
        "<!-- GENERATED by claude-power-pack -->\n---\nname: flow-start\n---\nold body\n",
        encoding="utf-8",
    )
    findings = {f["skill"]: f["status"] for f in fss.classify(skills, COMMANDS)}
    assert findings["flow-start"] == fss.DRIFTED


# --------------------------------------------------------------------------- #
# Generated content shape
# --------------------------------------------------------------------------- #
def test_generated_marker_and_frontmatter(tmp_path):
    skills = tmp_path / "skills"
    _write(skills)
    text = (skills / "flow-start" / "SKILL.md").read_text(encoding="utf-8")

    # Marker keeps skill-drift.py's is_generated() classification working.
    assert fss.MARKER_PREFIX in text
    assert "source_sha256:" in text
    assert "family: flow" in text
    assert "source: .claude/commands/flow/start.md" in text
    # Native-worktree body carried through; stale mechanics gone.
    assert "EnterWorktree" in text
    assert "WORKTREE_DIR" not in text
    assert "Plane" not in text


def test_marker_is_em_dash_free(tmp_path):
    """The generated marker is repo-authored, so it must use a plain hyphen."""
    skills = tmp_path / "skills"
    _write(skills)
    em_dash, en_dash = chr(0x2014), chr(0x2013)
    for p in skills.glob("flow-*/SKILL.md"):
        marker_line = p.read_text(encoding="utf-8").splitlines()[0]
        assert fss.MARKER_PREFIX in marker_line
        assert em_dash not in marker_line
        assert en_dash not in marker_line


# --------------------------------------------------------------------------- #
# Frontmatter stripping
# --------------------------------------------------------------------------- #
def test_strip_leading_frontmatter():
    with_fm = "---\ndescription: x\nallowed-tools: Bash\n---\n\n# Heading\n\nbody\n"
    assert fss._strip_leading_frontmatter(with_fm) == "# Heading\n\nbody\n"

    without_fm = "# Heading\n\nbody\n"
    assert fss._strip_leading_frontmatter(without_fm) == without_fm
