"""Tests for scripts/retired-surface-prune.py (issue #575).

What this guards: CPP retires a generated surface by deleting the generator
from the repo - but every copy that generator already wrote into a user's HOME
stays where it was, unmaintained and silently loading. Codex was still reading
65 prompts from a surface retired at the #556 cutover; 49 generated skills
frozen at 2026-07-04 were still loading alongside the current surface
(#480/#481).

The script deletes nothing: it MOVES owned files to a timestamped sibling
directory. The tests below concentrate on the three safety properties, because
this is the one CPP script that reaches into HOME:

  1. CURATED    - only directories listed in the YAML are inspected at all
  2. MARKER-GATED - within a listed directory, only files carrying a CPP
                    GENERATED header are owned; everything else is preserved
  3. REVERSIBLE - prune moves, never deletes

Everything runs on hermetic tmp trees with a synthetic surfaces file. No
network, no git, no HOME access, no external binaries - so this suite is safe
in the uv:python3.11-slim validate container (the #451/#489 trap).
"""

from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "retired-surface-prune.py"
REAL_SURFACES = ROOT / ".claude" / "retired-surfaces.yaml"

CODEX_MARKER = "<!-- GENERATED by claude-power-pack - scripts/codex-prompt-sync.py"
FLOW_MARKER = "<!-- GENERATED by claude-power-pack - scripts/flow-skill-sync.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("retired_surface_prune", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["retired_surface_prune"] = module
    spec.loader.exec_module(module)
    return module


rsp = _load_module()


# --- fixtures ----------------------------------------------------------------


@pytest.fixture
def flat_surface(tmp_path: Path):
    """A retired flat surface: two CPP-generated prompts + one hand-authored."""
    surface = tmp_path / "prompts"
    surface.mkdir()
    (surface / "flow-auto.md").write_text(f"{CODEX_MARKER}; edit x instead -->\n# generated\n")
    (surface / "qa-test.md").write_text(f"{CODEX_MARKER}; edit y instead -->\n# generated\n")
    (surface / "cpp-memory.md").write_text("# Hand-authored, installed by install-memory-harness.sh\n")
    yaml = tmp_path / "surfaces.yaml"
    yaml.write_text(
        "version: 1\n"
        "retired:\n"
        "  - name: codex-prompts\n"
        f"    path: {surface}\n"
        "    depth: flat\n"
        "    markers:\n"
        f'      - "{CODEX_MARKER}"\n'
        "    reason: retired at the cutover\n"
        "    preserve:\n"
        "      - cpp-memory.md\n"
    )
    return surface, yaml


@pytest.fixture
def dirs_surface(tmp_path: Path):
    """A retired dir-per-unit surface: one generated skill + one the user wrote."""
    surface = tmp_path / "skills"
    (surface / "flow-auto").mkdir(parents=True)
    (surface / "flow-auto" / "SKILL.md").write_text(
        f"---\nname: flow-auto\n---\n{FLOW_MARKER}; edit z instead -->\n# generated\n"
    )
    (surface / "my-skill").mkdir()
    (surface / "my-skill" / "SKILL.md").write_text("---\nname: mine\n---\n# I wrote this\n")
    yaml = tmp_path / "surfaces.yaml"
    yaml.write_text(
        "version: 1\n"
        "retired:\n"
        "  - name: claude-skills-mirror\n"
        f"    path: {surface}\n"
        "    depth: dirs\n"
        "    entry_file: SKILL.md\n"
        "    markers:\n"
        f'      - "{FLOW_MARKER}"\n'
        "    reason: mirror retired in B4\n"
    )
    return surface, yaml


# --- wiring ------------------------------------------------------------------


def test_script_exists_and_executable():
    assert SCRIPT.is_file(), f"missing {SCRIPT}"
    assert os.access(SCRIPT, os.X_OK)


def test_real_surfaces_file_is_loadable_and_complete():
    entries = rsp.load_surfaces(REAL_SURFACES)
    names = {e["name"] for e in entries}
    assert names == {"codex-prompts", "claude-skills-mirror"}, names
    for entry in entries:
        assert entry.get("path"), entry
        assert entry.get("markers"), f"{entry['name']} has no markers - it could never own anything"
        assert entry.get("reason"), entry["name"]


def test_real_surfaces_markers_match_the_deleted_generators():
    """A guessed marker fails SAFE but is useless. These are the literal strings
    the deleted generators emitted, recovered from git history."""
    entries = {e["name"]: e for e in rsp.load_surfaces(REAL_SURFACES)}
    assert any(m.startswith(CODEX_MARKER) for m in entries["codex-prompts"]["markers"])
    assert any(m.startswith(FLOW_MARKER) for m in entries["claude-skills-mirror"]["markers"])


def test_fallback_parser_matches_pyyaml_on_the_real_file():
    """The script must work with bare python3 on a host without PyYAML."""
    text = REAL_SURFACES.read_text(encoding="utf-8")
    fallback = rsp._fallback_parse(text)
    try:
        import yaml
    except ImportError:
        pytest.skip("PyYAML not installed - nothing to compare against")
    real = yaml.safe_load(text)
    assert [e["name"] for e in fallback["retired"]] == [e["name"] for e in real["retired"]]
    for fb, rl in zip(fallback["retired"], real["retired"]):
        assert fb["path"] == rl["path"]
        assert fb["depth"] == rl["depth"]
        assert fb["markers"] == rl["markers"]
        assert fb.get("preserve", []) == rl.get("preserve", [])


# --- ownership ---------------------------------------------------------------


def test_flat_surface_owns_only_marked_files(flat_surface):
    surface, yaml = flat_surface
    report = rsp.scan_surface(rsp.load_surfaces(yaml)[0])
    assert report["status"] == rsp.STATUS_OWNED
    assert sorted(report["owned"]) == ["flow-auto.md", "qa-test.md"]
    assert "cpp-memory.md" in report["preserved"]


def test_dirs_surface_owns_only_marked_dirs(dirs_surface):
    surface, yaml = dirs_surface
    report = rsp.scan_surface(rsp.load_surfaces(yaml)[0])
    assert report["owned"] == ["flow-auto"]
    assert report["preserved"] == ["my-skill"]


def test_marker_is_found_behind_yaml_frontmatter(tmp_path: Path):
    f = tmp_path / "x.md"
    f.write_text(f"---\nname: x\ndescription: y\n---\n{FLOW_MARKER} -->\n# body\n")
    assert rsp.is_owned(f, [FLOW_MARKER])


def test_unmarked_file_is_never_owned(tmp_path: Path):
    f = tmp_path / "x.md"
    f.write_text("# just a document that mentions claude-power-pack\n")
    assert not rsp.is_owned(f, [FLOW_MARKER])


def test_marker_mentioned_mid_body_does_not_confer_ownership(tmp_path: Path):
    """Only the FIRST content line counts - prose quoting the marker must not
    make a hand-written file look generated."""
    f = tmp_path / "x.md"
    f.write_text(f"# My notes\n\nCPP writes `{FLOW_MARKER}` at the top of generated files.\n")
    assert not rsp.is_owned(f, [FLOW_MARKER])


def test_absent_directory_is_reported_not_an_error(tmp_path: Path):
    yaml = tmp_path / "s.yaml"
    yaml.write_text(
        "version: 1\nretired:\n  - name: gone\n"
        f"    path: {tmp_path / 'nope'}\n    depth: flat\n"
        f'    markers:\n      - "{CODEX_MARKER}"\n    reason: x\n'
    )
    report = rsp.scan_surface(rsp.load_surfaces(yaml)[0])
    assert report["status"] == rsp.STATUS_ABSENT
    assert report["owned"] == []


def test_surface_with_only_handauthored_files_is_clean(tmp_path: Path):
    surface = tmp_path / "prompts"
    surface.mkdir()
    (surface / "cpp-memory.md").write_text("# hand authored\n")
    yaml = tmp_path / "s.yaml"
    yaml.write_text(
        "version: 1\nretired:\n  - name: codex-prompts\n"
        f"    path: {surface}\n    depth: flat\n"
        f'    markers:\n      - "{CODEX_MARKER}"\n    reason: x\n'
    )
    report = rsp.scan_surface(rsp.load_surfaces(yaml)[0])
    assert report["status"] == rsp.STATUS_CLEAN


# --- plan is pure ------------------------------------------------------------


def test_plan_changes_nothing_on_disk(flat_surface):
    surface, yaml = flat_surface
    before = sorted(p.name for p in surface.iterdir())
    entries = rsp.load_surfaces(yaml)
    lines = rsp.plan_prune(rsp.scan_surface(entries[0]), "2026-07-19")
    assert any(line.startswith("mv ") for line in lines)
    assert sorted(p.name for p in surface.iterdir()) == before


# --- prune -------------------------------------------------------------------


def test_prune_moves_owned_and_preserves_the_rest(flat_surface):
    surface, yaml = flat_surface
    entries = rsp.load_surfaces(yaml)
    assert rsp.prune(entries, ["codex-prompts"], "2026-07-19") == 0

    assert (surface / "cpp-memory.md").is_file(), "hand-authored file was moved"
    assert not (surface / "flow-auto.md").exists()
    assert not (surface / "qa-test.md").exists()

    retired = surface.parent / f"{surface.name}-retired-2026-07-19"
    assert (retired / "flow-auto.md").is_file()
    assert (retired / "qa-test.md").is_file()


def test_prune_is_reversible(flat_surface):
    """The whole safety story: nothing is deleted, so a mistake is recoverable."""
    surface, yaml = flat_surface
    original = (surface / "flow-auto.md").read_text()
    rsp.prune(rsp.load_surfaces(yaml), ["codex-prompts"], "2026-07-19")
    retired = surface.parent / f"{surface.name}-retired-2026-07-19"
    (retired / "flow-auto.md").rename(surface / "flow-auto.md")
    assert (surface / "flow-auto.md").read_text() == original


def test_prune_dirs_surface_keeps_user_skill(dirs_surface):
    surface, yaml = dirs_surface
    rsp.prune(rsp.load_surfaces(yaml), ["claude-skills-mirror"], "2026-07-19")
    assert (surface / "my-skill" / "SKILL.md").is_file()
    assert not (surface / "flow-auto").exists()
    assert (surface.parent / f"{surface.name}-retired-2026-07-19" / "flow-auto" / "SKILL.md").is_file()


def test_prune_refuses_a_surface_not_in_the_list_of_record(flat_surface, capsys):
    surface, yaml = flat_surface
    rc = rsp.prune(rsp.load_surfaces(yaml), ["some-other-directory"], "2026-07-19")
    assert rc == 1
    assert "REFUSED" in capsys.readouterr().err
    assert sorted(p.name for p in surface.iterdir()) == ["cpp-memory.md", "flow-auto.md", "qa-test.md"]


def test_prune_refuses_a_clean_surface(tmp_path: Path, capsys):
    surface = tmp_path / "prompts"
    surface.mkdir()
    (surface / "mine.md").write_text("# hand authored\n")
    yaml = tmp_path / "s.yaml"
    yaml.write_text(
        "version: 1\nretired:\n  - name: codex-prompts\n"
        f"    path: {surface}\n    depth: flat\n"
        f'    markers:\n      - "{CODEX_MARKER}"\n    reason: x\n'
    )
    assert rsp.prune(rsp.load_surfaces(yaml), ["codex-prompts"], "2026-07-19") == 1
    assert "REFUSED" in capsys.readouterr().err
    assert (surface / "mine.md").is_file()


# --- CLI ---------------------------------------------------------------------


def _run(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def test_cli_check_exits_1_on_findings(flat_surface):
    surface, yaml = flat_surface
    res = _run("--check", "--surfaces-file", str(yaml))
    assert res.returncode == 1
    assert rsp.STATUS_OWNED in res.stdout


def test_cli_check_exits_0_when_clean(dirs_surface, tmp_path):
    surface, yaml = dirs_surface
    (surface / "flow-auto" / "SKILL.md").write_text("---\nname: x\n---\n# not generated\n")
    res = _run("--check", "--surfaces-file", str(yaml))
    assert res.returncode == 0


def test_cli_json_is_parseable(flat_surface):
    surface, yaml = flat_surface
    res = _run("--json", "--surfaces-file", str(yaml))
    assert res.returncode == 0
    payload = json.loads(res.stdout)
    assert payload["surfaces"][0]["name"] == "codex-prompts"
    assert sorted(payload["surfaces"][0]["owned"]) == ["flow-auto.md", "qa-test.md"]


def test_cli_real_repo_check_runs(tmp_path):
    """The shipped list of record must at minimum load and classify cleanly."""
    res = _run("--check")
    assert res.returncode in (0, 1), res.stderr
    assert "codex-prompts" in res.stdout
