"""Regression tests for the surviving install-drift jobs (#622/#662).

The marketplace clone/cache parity walk retired with that distribution lane,
but installed helpers remain byte-compared with checkout helpers through the
symlink restoration in #663. Retired marketplace state is still reported as a
non-failing migration finding. All cases run on hermetic HOME/checkout trees.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

from tests.helper_exit_line import without_status

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "install-drift.sh"
HELPER = "flow-start-resolve.sh"
HELPER_BODY = "#!/usr/bin/env bash\necho resolve\n"

pytestmark = pytest.mark.skipif(
    shutil.which("bash") is None, reason="requires bash on PATH"
)


def _make_checkout(root: Path) -> Path:
    """A post-#662 checkout deliberately has no plugins/ directory."""
    (root / ".claude" / "commands" / "flow").mkdir(parents=True)
    (root / "scripts").mkdir()
    (root / "CLAUDE.md").write_text("# fake CPP\n", encoding="utf-8")
    (root / ".claude" / "commands" / "flow" / "auto.md").write_text(
        "# auto\n", encoding="utf-8"
    )
    (root / "scripts" / HELPER).write_text(HELPER_BODY, encoding="utf-8")
    return root


def _make_cache(home: Path, *families: str) -> Path:
    cache = home / ".claude" / "plugins" / "cache" / "cpp"
    for family in families:
        commands = cache / family / "1.1.0" / "commands"
        commands.mkdir(parents=True)
        (commands / "help.md").write_text("# stale snapshot\n", encoding="utf-8")
    return cache


def _make_helpers(home: Path) -> Path:
    scripts = home / ".claude" / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    (scripts / HELPER).write_text(HELPER_BODY, encoding="utf-8")
    return scripts


def _install_real_flow_helpers_installer(checkout: Path) -> Path:
    """Copy the REAL scripts/flow-helpers-install.sh into a fake checkout.

    It is a general-purpose, self-contained script (env-seamed via
    FLOW_HELPERS_HOME/FLOW_HELPERS_SOURCE) with no install-drift-specific
    coupling, so tests exercise the actual HELPERS membership list - the
    same one production install-drift.sh shells out to - rather than a
    fabricated one (issue #828).
    """
    real = ROOT / "scripts" / "flow-helpers-install.sh"
    dest = checkout / "scripts" / "flow-helpers-install.sh"
    dest.write_bytes(real.read_bytes())
    dest.chmod(0o755)
    return dest


# codex-skill-sync.py's own marker, byte-for-byte (issue #823): a real
# installed skill only ever carries this exact prefix, and the ownership
# boundary depends on the script matching it precisely.
CODEX_SKILL_MARKER = (
    "<!-- GENERATED by claude-power-pack - scripts/codex-skill-sync.py;"
    " edit .claude/commands/cpp/help.md instead -->"
)


def _make_codex_skill_source(checkout: Path, name: str, *, body: str = "body\n") -> Path:
    """A CPP-shipped Codex skill package under <checkout>/codex/skills/<name>/."""
    pkg = checkout / "codex" / "skills" / name
    pkg.mkdir(parents=True, exist_ok=True)
    (pkg / "SKILL.md").write_text(
        f"---\nname: {name}\n---\n{CODEX_SKILL_MARKER}\n{body}", encoding="utf-8"
    )
    return pkg


def _make_codex_skill_installed(
    home: Path, name: str, *, body: str = "body\n", managed: bool = True
) -> Path:
    """An installed package under ~/.codex/skills/<name>/.

    ``managed=False`` omits the GENERATED marker - a host-owned or
    Codex-installed package, never ours to judge as drift or orphan.
    """
    pkg = home / ".codex" / "skills" / name
    pkg.mkdir(parents=True, exist_ok=True)
    marker = f"{CODEX_SKILL_MARKER}\n" if managed else ""
    (pkg / "SKILL.md").write_text(
        f"---\nname: {name}\n---\n{marker}{body}", encoding="utf-8"
    )
    return pkg


def _run(checkout: Path, home: Path, *args: str, script: Path | None = None):
    return subprocess.run(
        ["bash", str(script or SCRIPT), *args],
        env={
            "CPP_INSTALL_DRIFT_CHECKOUT": str(checkout),
            "CPP_INSTALL_DRIFT_HOME": str(home),
            "PATH": os.environ.get("PATH", ""),
        },
        stdin=subprocess.DEVNULL,
        capture_output=True,
        text=True,
    )


def test_stale_helper_is_real_drift_in_every_output_mode(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    scripts = _make_helpers(home)
    (scripts / HELPER).write_text(
        "#!/usr/bin/env bash\necho OLD\n", encoding="utf-8"
    )

    report = _run(checkout, home)
    quiet = _run(checkout, home, "--quiet")
    json_result = _run(checkout, home, "--json")
    payload = json.loads(json_result.stdout)

    assert report.returncode == 0, report.stdout + report.stderr
    assert "0 current, 1 stale" in report.stdout
    assert f"Stale helpers: {HELPER}" in report.stdout
    assert "INSTALL_DRIFT: drift" in report.stdout
    assert quiet.returncode == 0
    assert quiet.stdout.splitlines() == [
        "CPP install: 1 helper(s) stale - run /cpp:update"
    ]
    assert json_result.returncode == 0
    assert payload["verdict"] == "drift"
    assert payload["helpers_stale"] == 1
    assert payload["stale_helpers"] == [HELPER]


def test_host_only_scripts_are_not_judged(tmp_path: Path):
    # A script the user put in ~/.claude/scripts that CPP does not ship is none
    # of this check's business - flagging it would make the check cry wolf.
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    scripts = _make_helpers(home)
    (scripts / "my-own-tool.sh").write_text("#!/bin/sh\necho host\n", encoding="utf-8")

    result = _run(checkout, home)

    assert result.returncode == 0
    assert "1 current, 0 stale" in result.stdout
    assert "my-own-tool.sh" not in result.stdout
    assert "INSTALL_DRIFT: ok" in result.stdout


def test_split_install_is_named_with_current_helpers_and_retired_cache(tmp_path: Path):
    # The two independently installed halves from #622 remain visible during
    # migration: helpers can match the checkout while the old command cache is
    # still present. Cache contents are no longer judged after #662.
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_helpers(home)
    _make_cache(home, "flow")

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0
    assert "SPLIT INSTALL" in report.stdout
    assert "1 current, 0 stale" in report.stdout
    assert "INSTALL_DRIFT: skipped" in report.stdout
    assert payload["split"] is True


def test_stale_helpers_and_retired_cache_coexist_with_drift_dominant(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    scripts = _make_helpers(home)
    (scripts / HELPER).write_text("#!/bin/sh\necho stale\n", encoding="utf-8")
    _make_cache(home, "flow")

    report = _run(checkout, home)
    quiet = _run(checkout, home, "--quiet")
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert "Stale helpers" in report.stdout
    assert "/plugin uninstall flow@cpp" in report.stdout
    assert "INSTALL_DRIFT: drift" in report.stdout
    assert len(quiet.stdout.splitlines()) == 1
    assert "1 helper(s) stale" in quiet.stdout
    assert "retired marketplace surface" in quiet.stdout
    assert payload["verdict"] == "drift"
    assert payload["cache_families"] == ["flow"]


def test_plugins_less_checkout_with_lingering_cache_is_retired_info(tmp_path: Path):
    """The #662 regression: removed checkout sources must not crash the walk."""
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_cache(home, "flow")

    result = _run(checkout, home)

    assert result.returncode == 0, result.stdout + result.stderr
    assert "retired CPP marketplace surface" in result.stdout
    assert "/plugin uninstall flow@cpp" in result.stdout
    assert "INSTALL_DRIFT: skipped" in result.stdout
    assert "drift" not in without_status(result.stderr).lower()


def test_multiple_cached_families_are_named(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_cache(home, "flow", "security")

    result = _run(checkout, home)

    assert result.returncode == 0
    assert "installed families flow security" in result.stdout
    assert "/plugin uninstall flow@cpp" in result.stdout
    assert "/plugin uninstall security@cpp" in result.stdout


def test_quiet_retired_cache_is_one_non_failing_line(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_cache(home, "flow", "security")

    result = _run(checkout, home, "--quiet")

    assert result.returncode == 0
    lines = [line for line in result.stdout.splitlines() if line.strip()]
    assert lines == [
        "CPP install: retired marketplace surface pending uninstall (#662/#663): flow,security"
    ]


def test_no_retired_surface_is_skipped_silently_in_quiet_mode(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    home.mkdir()

    report = _run(checkout, home)
    quiet = _run(checkout, home, "--quiet")

    assert report.returncode == 0
    assert "INSTALL_DRIFT: skipped" in report.stdout
    assert quiet.returncode == 0
    assert quiet.stdout == ""


def test_marketplace_clone_is_reported_without_cache(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    (home / ".claude" / "plugins" / "marketplaces" / "cpp").mkdir(parents=True)

    report = _run(checkout, home)
    quiet = _run(checkout, home, "--quiet")

    assert report.returncode == 0
    assert "marketplace clone" in report.stdout
    assert "(retired)" in report.stdout
    assert quiet.stdout.count("\n") == 1
    assert "retired marketplace clone" in quiet.stdout


def test_json_reports_skipped_retired_surface(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_cache(home, "flow")

    result = _run(checkout, home, "--json")
    payload = json.loads(result.stdout)

    assert result.returncode == 0
    assert payload["verdict"] == "skipped"
    assert payload["reason"] == "retired marketplace surface"
    assert payload["cache_families"] == ["flow"]


def test_no_checkout_is_skipped_not_failed(tmp_path: Path):
    home = tmp_path / "home"
    _make_cache(home, "flow")
    bin_dir = tmp_path / "elsewhere" / "bin"
    bin_dir.mkdir(parents=True)
    copied_script = bin_dir / "install-drift.sh"
    shutil.copy(SCRIPT, copied_script)

    result = subprocess.run(
        ["bash", str(copied_script)],
        env={"CPP_INSTALL_DRIFT_HOME": str(home), "PATH": os.environ.get("PATH", "")},
        stdin=subprocess.DEVNULL,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0
    assert "no CPP checkout" in result.stdout
    assert "INSTALL_DRIFT: skipped" in result.stdout


def test_bad_checkout_override_is_an_error(tmp_path: Path):
    home = tmp_path / "home"
    _make_cache(home, "flow")

    result = _run(tmp_path / "not-a-checkout", home)

    assert result.returncode == 2
    assert "INSTALL_DRIFT: error" in result.stdout


def test_check_never_writes(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_cache(home, "flow")

    def snapshot(root: Path):
        return {
            str(path.relative_to(root)): path.read_bytes()
            for path in sorted(root.rglob("*"))
            if path.is_file()
        }

    before = snapshot(checkout), snapshot(home)
    _run(checkout, home)
    assert (snapshot(checkout), snapshot(home)) == before


# --------------------------------------------------------------------------
# Installed Codex skill parity (issue #823) - a COPY made by
# codex-skill-sync.py --install, not a symlink; git pull cannot refresh it.
# --------------------------------------------------------------------------


def test_stale_codex_skill_is_drift_in_every_output_mode(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_codex_skill_source(checkout, "cpp-status", body="current text\n")
    _make_codex_skill_installed(home, "cpp-status", body="STALE text\n")

    report = _run(checkout, home)
    quiet = _run(checkout, home, "--quiet")
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0, report.stdout + report.stderr
    assert "Stale Codex skills: cpp-status" in report.stdout
    assert "Reconcile stale Codex skills" in report.stdout
    assert "INSTALL_DRIFT: drift" in report.stdout
    assert quiet.returncode == 0
    assert "1 Codex skill(s) stale" in quiet.stdout
    assert payload["verdict"] == "drift"
    assert payload["codex_skills_stale"] == 1
    assert payload["stale_codex_skills"] == ["cpp-status"]
    assert payload["codex_skills_checked"] is True


def test_current_codex_skills_report_ok(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_codex_skill_source(checkout, "cpp-help", body="same\n")
    _make_codex_skill_installed(home, "cpp-help", body="same\n")

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0
    assert "1 current, 0 stale, 0 orphaned" in report.stdout
    assert "INSTALL_DRIFT: ok" in report.stdout
    assert payload["verdict"] == "ok"
    assert payload["codex_skills_current"] == 1
    assert payload["codex_skills_checked"] is True


def test_dotted_system_skills_are_never_judged(tmp_path: Path):
    # Codex CLI's own built-ins live under ~/.codex/skills/.system/ - never
    # ours, never flagged, even with content that matches nothing this
    # checkout ships.
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_helpers(home)  # forces the full report path, not the terse global skip
    system_pkg = home / ".codex" / "skills" / ".system" / "skill-installer"
    system_pkg.mkdir(parents=True)
    (system_pkg / "SKILL.md").write_text("not ours at all\n", encoding="utf-8")

    result = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert result.returncode == 0
    assert "skill-installer" not in result.stdout
    assert payload["codex_skills_current"] == 0
    assert payload["codex_skills_stale"] == 0
    assert payload["codex_skills_orphaned"] == 0
    assert payload["codex_skills_checked"] is False


def test_host_only_codex_skill_is_not_judged(tmp_path: Path):
    # An installed package this checkout never shipped, carrying no GENERATED
    # marker, is genuinely none of this check's business - neither drift nor
    # an orphan of ours.
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_helpers(home)  # forces the full report path, not the terse global skip
    _make_codex_skill_installed(home, "some-other-tool", body="hi\n", managed=False)

    result = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert result.returncode == 0
    assert "some-other-tool" not in result.stdout
    assert payload["codex_skills_orphaned"] == 0
    assert payload["codex_skills_checked"] is False


def test_empty_codex_skills_tree_is_not_reported_ok(tmp_path: Path):
    # The membership floor (#823): an existing-but-empty install tree must
    # never read as "checked, clean". Helpers are current too, so the overall
    # script still renders the full report rather than the terse skip - the
    # floor is about THIS job never claiming clean on its own, not about
    # forcing the whole script pessimistic.
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_helpers(home)
    (home / ".codex" / "skills").mkdir(parents=True)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0
    assert "not installed or empty - nothing to check" in report.stdout
    assert payload["codex_skills_checked"] is False
    assert payload["verdict"] == "ok"


def test_absent_codex_skills_tree_does_not_defeat_the_global_skip(tmp_path: Path):
    """Regression guard: nothing installed of any of the three kinds still
    hits the terse emit_skip path exactly as it did before #823."""
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    home.mkdir()

    result = _run(checkout, home)

    assert result.returncode == 0
    assert "INSTALL_DRIFT: skipped" in result.stdout
    assert (
        "no retired CPP marketplace surface, installed checkout helpers, "
        "or installed Codex/Claude skills found" in result.stdout
    )


def test_codex_skills_present_alone_avoids_the_terse_skip(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_codex_skill_source(checkout, "cpp-help", body="same\n")
    _make_codex_skill_installed(home, "cpp-help", body="same\n")

    result = _run(checkout, home)

    assert result.returncode == 0
    assert "install-drift: checkout" in result.stdout  # full report, not the terse skip
    assert "INSTALL_DRIFT: ok" in result.stdout


def test_orphaned_codex_skill_is_reported_but_not_drift(tmp_path: Path):
    # A managed package with no repo counterpart - this checkout used to ship
    # it, deleted it from codex/skills/, and it was never pruned from the
    # install tree. Reported, but informational (a prune, not a re-install).
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_codex_skill_installed(home, "cpp-retired-thing", body="gone\n", managed=True)

    report = _run(checkout, home)
    quiet = _run(checkout, home, "--quiet")
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0
    assert "Orphaned Codex skills" in report.stdout
    assert "cpp-retired-thing" in report.stdout
    assert "INSTALL_DRIFT: skipped" in report.stdout
    assert payload["verdict"] == "skipped"
    assert payload["reason"] == "orphaned Codex skills"
    assert payload["codex_skills_orphaned"] == 1
    assert payload["orphaned_codex_skills"] == ["cpp-retired-thing"]
    assert "orphaned" in quiet.stdout


def test_json_reports_codex_skills_fields(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_codex_skill_source(checkout, "cpp-help", body="same\n")
    _make_codex_skill_installed(home, "cpp-help", body="same\n")
    _make_codex_skill_source(checkout, "cpp-status", body="fresh\n")
    _make_codex_skill_installed(home, "cpp-status", body="stale\n")
    _make_codex_skill_installed(home, "cpp-retired-thing", body="gone\n", managed=True)

    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["codex_skills_checked"] is True
    assert payload["codex_skills_current"] == 1
    assert payload["codex_skills_stale"] == 1
    assert set(payload["stale_codex_skills"]) == {"cpp-status"}
    assert payload["codex_skills_orphaned"] == 1
    assert payload["orphaned_codex_skills"] == ["cpp-retired-thing"]
    assert payload["verdict"] == "drift"  # stale takes priority over the orphan


def test_missing_helper_is_drift_in_every_output_mode(tmp_path: Path):
    # The actual #828 incident: delegated-run-check.sh shipped by the
    # checkout, never installed at all.
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_flow_helpers_installer(checkout)
    (checkout / "scripts" / "delegated-run-check.sh").write_text(
        "#!/usr/bin/env bash\necho check\n", encoding="utf-8"
    )
    home = tmp_path / "home"
    scripts = _make_helpers(home)  # the pre-existing HELPER stays installed and current
    # The installer is itself in HELPERS; keep it installed for this scenario.
    shutil.copy2(checkout / "scripts" / "flow-helpers-install.sh", scripts)

    report = _run(checkout, home)
    quiet = _run(checkout, home, "--quiet")
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0, report.stdout + report.stderr
    assert "Missing helpers: delegated-run-check.sh" in report.stdout
    assert "Reconcile stale or missing helpers" in report.stdout
    assert "INSTALL_DRIFT: drift" in report.stdout
    assert quiet.returncode == 0
    assert "1 helper(s) missing" in quiet.stdout
    assert payload["verdict"] == "drift"
    assert payload["helpers_missing"] == 1
    assert payload["missing_helpers"] == ["delegated-run-check.sh"]
    assert payload["helpers_missing_checked"] is True


def test_missing_and_stale_coexist_both_named_separately(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_flow_helpers_installer(checkout)
    (checkout / "scripts" / "delegated-run-check.sh").write_text(
        "#!/usr/bin/env bash\necho check\n", encoding="utf-8"
    )
    home = tmp_path / "home"
    scripts = _make_helpers(home)
    # The installer is itself in HELPERS; keep it installed for this scenario.
    shutil.copy2(checkout / "scripts" / "flow-helpers-install.sh", scripts)
    (scripts / HELPER).write_text("#!/bin/sh\necho stale\n", encoding="utf-8")

    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["verdict"] == "drift"
    assert payload["helpers_stale"] == 1
    assert payload["stale_helpers"] == [HELPER]
    assert payload["helpers_missing"] == 1
    assert payload["missing_helpers"] == ["delegated-run-check.sh"]


def test_non_helpers_array_checkout_script_is_never_reported_missing(tmp_path: Path):
    # secrets-mask.sh is a real scripts/*.sh file NOT in flow-helpers-install.sh's
    # HELPERS array (opt-in/dev-only) - never installed here, must never be
    # flagged as missing. This is the ownership-boundary regression guard.
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_flow_helpers_installer(checkout)
    (checkout / "scripts" / "secrets-mask.sh").write_text(
        "#!/usr/bin/env bash\necho mask\n", encoding="utf-8"
    )
    home = tmp_path / "home"
    scripts = _make_helpers(home)
    # The installer is itself in HELPERS; keep it installed for this scenario.
    shutil.copy2(checkout / "scripts" / "flow-helpers-install.sh", scripts)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0
    assert "secrets-mask.sh" not in report.stdout
    assert payload["helpers_missing"] == 0
    assert payload["verdict"] == "ok"


def test_missing_check_unavailable_when_installer_absent(tmp_path: Path):
    # Every EXISTING test's fixture (no flow-helpers-install.sh copied in) -
    # proves every pre-#828 test stays valid: fails open, never "0 missing".
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_helpers(home)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0
    assert "missing-helper check unavailable" in report.stdout
    assert "not found in checkout" in report.stdout
    assert payload["helpers_missing_checked"] is False
    assert payload["helpers_missing"] == 0
    assert payload["verdict"] == "ok"


def test_missing_check_unavailable_when_installer_output_unparseable(tmp_path: Path):
    # The installer is present but its --check output format is unrecognised
    # (a future format change, or something else entirely) - must read as
    # "ran and parsed nothing", not "ran, found 0 missing" (issue #828 review).
    checkout = _make_checkout(tmp_path / "checkout")
    stub = checkout / "scripts" / "flow-helpers-install.sh"
    stub.write_text(
        "#!/usr/bin/env bash\necho 'SOMETHING WEIRD'\nexit 0\n", encoding="utf-8"
    )
    stub.chmod(0o755)
    home = tmp_path / "home"
    _make_helpers(home)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0
    assert "missing-helper check unavailable" in report.stdout
    assert "no recognisable output" in report.stdout
    assert payload["helpers_missing_checked"] is False
    assert payload["helpers_missing"] == 0
    assert payload["verdict"] == "ok"


def test_wholly_uninstalled_helper_family_avoids_the_terse_skip(tmp_path: Path):
    # The sharpest case: nothing installed AT ALL. The old compound skip
    # would have read this as "nothing to report" - the worst case of
    # missing, at 100% rather than 1-of-36, invisible by the same gap.
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_flow_helpers_installer(checkout)
    (checkout / "scripts" / "delegated-run-check.sh").write_text(
        "#!/usr/bin/env bash\necho check\n", encoding="utf-8"
    )
    home = tmp_path / "home"
    home.mkdir()  # nothing installed anywhere

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert report.returncode == 0
    assert "install-drift: checkout" in report.stdout  # full report, not emit_skip
    assert "Missing helpers:" in report.stdout
    assert "delegated-run-check.sh" in report.stdout
    assert "INSTALL_DRIFT: drift" in report.stdout
    assert payload["verdict"] == "drift"
    assert payload["helpers_missing"] >= 1


def test_split_install_requires_no_missing_helpers(tmp_path: Path):
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_flow_helpers_installer(checkout)
    (checkout / "scripts" / "delegated-run-check.sh").write_text(
        "#!/usr/bin/env bash\necho check\n", encoding="utf-8"
    )
    home = tmp_path / "home"
    _make_helpers(home)
    _make_cache(home, "flow")

    payload = json.loads(_run(checkout, home, "--json").stdout)

    # A missing helper means the SPLIT claim ("helpers match the checkout")
    # would be false - SPLIT must not fire.
    assert payload["split"] is False


def test_modified_non_sh_helper_is_reported_stale(tmp_path: Path):
    # flow-wave-plan.py is the one non-.sh entry in flow-helpers-install.sh's
    # HELPERS array - the stale/current loop's glob widened from *.sh to *
    # (filtered to regular files) so it is judged for content too, not just
    # presence. This is exactly the file a 20-vs-21 membership-count
    # reconcile surfaced as having asymmetric coverage (issue #828 review).
    # A .sh control sits alongside it so the pre-existing behaviour is pinned
    # too, not just assumed to still work.
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_flow_helpers_installer(checkout)
    (checkout / "scripts" / "flow-wave-plan.py").write_text(
        "# current\n", encoding="utf-8"
    )
    home = tmp_path / "home"
    scripts = _make_helpers(home)
    shutil.copy2(checkout / "scripts" / "flow-helpers-install.sh", scripts)
    (scripts / "flow-wave-plan.py").write_text("# STALE\n", encoding="utf-8")
    (scripts / HELPER).write_text("#!/bin/sh\necho stale\n", encoding="utf-8")

    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["verdict"] == "drift"
    assert set(payload["stale_helpers"]) == {"flow-wave-plan.py", HELPER}
    assert payload["helpers_missing"] == 0
    assert payload["verdict"] == "drift"


# ---------------------------------------------------------------------------
# Job 4: installed ~/.claude/skills parity (issue #1029, specimen 5)
#
# `install-drift` covered ~/.codex/skills and not ~/.claude/skills, and the
# asymmetry was the tell: the right comparison was already implemented for one
# root and simply not pointed at the other. That root is user-scope - its
# packages load in EVERY project - it holds real directories rather than
# symlinks, and ~/.claude is not a git repository, so nothing on the host could
# diff them.
#
# The controls are the two ends plus the ownership boundary, and the boundary is
# the interesting one: ~/.claude/skills/boot on the reference host is a
# DIFFERENT project's skill colliding by name with CPP's .claude/skills/boot. A
# name-keyed comparison would report it stale forever, and a job that cries wolf
# on every run is one nobody reads.
# ---------------------------------------------------------------------------

CANONICAL_SKILL = """\
---
name: demo
description: A demo skill package.
trigger: demo
metadata:
  provenance:
    class: cpp-authored
---

# Demo

Body.
"""

MANAGED_SKILL = """\
---
name: demo
description: A demo skill package.
trigger: demo
metadata:
  provenance:
    class: cpp-authored
  source: https://github.com/cooneycw/claude-power-pack/blob/main/.claude/skills/demo/SKILL.md
---

# Demo

Body.
"""

#: A package with no CPP marker at all - the `boot` collision, generalised.
UNMARKED_SKILL = """\
---
name: demo
description: Somebody else's package that happens to share our name.
trigger: demo
metadata:
  provenance:
    class: cpp-authored
---

# Demo

Entirely different body.
"""


def _install_real_skills_checker(checkout: Path) -> Path:
    """Copy the REAL scripts/skills-check.py into a fake checkout.

    install-drift shells out to the checker in the checkout it is judging, so a
    fake checkout needs the real one. Using the real script is the point: a stub
    would test this module's idea of the comparison rather than the comparison.
    """
    destination = checkout / "scripts" / "skills-check.py"
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / "scripts" / "skills-check.py", destination)
    return destination


def _make_canonical_skill(checkout: Path, name: str = "demo") -> Path:
    package = checkout / ".claude" / "skills" / name
    package.mkdir(parents=True)
    (package / "SKILL.md").write_text(CANONICAL_SKILL, encoding="utf-8")
    (package / "helper.sh").write_text("#!/bin/sh\necho helper\n", encoding="utf-8")
    return package


def _make_installed_skill(home: Path, body: str, name: str = "demo") -> Path:
    package = home / ".claude" / "skills" / name
    package.mkdir(parents=True)
    (package / "SKILL.md").write_text(body, encoding="utf-8")
    (package / "helper.sh").write_text("#!/bin/sh\necho helper\n", encoding="utf-8")
    return package


@pytest.mark.skipif(shutil.which("python3") is None, reason="requires python3 on PATH")
def test_negative_control_a_current_claude_skill_is_not_stale(tmp_path: Path):
    """The half that separates a working comparison from one matching nothing."""
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_skills_checker(checkout)
    _make_canonical_skill(checkout)
    home = tmp_path / "home"
    _make_installed_skill(home, MANAGED_SKILL)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["claude_skills_checked"] is True
    assert payload["claude_skills_managed"] == 1
    assert payload["claude_skills_clean"] == 1
    assert payload["claude_skills_stale"] == 0
    assert "1 CPP-marked, 1 clean, 0 stale" in report.stdout


@pytest.mark.skipif(shutil.which("python3") is None, reason="requires python3 on PATH")
def test_positive_control_a_modified_claude_skill_is_reported_stale(tmp_path: Path):
    """A payload file edited under ~/.claude/skills must be found."""
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_skills_checker(checkout)
    _make_canonical_skill(checkout)
    home = tmp_path / "home"
    installed = _make_installed_skill(home, MANAGED_SKILL)
    (installed / "helper.sh").write_text("#!/bin/sh\necho STALE\n", encoding="utf-8")

    report = _run(checkout, home)
    quiet = _run(checkout, home, "--quiet")
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["claude_skills_stale"] == 1
    assert payload["stale_claude_skills"] == ["demo"]
    assert payload["verdict"] == "drift"
    assert "Stale Claude skills: demo" in report.stdout
    assert "INSTALL_DRIFT: drift" in report.stdout
    assert "1 Claude skill(s) stale" in quiet.stdout


@pytest.mark.skipif(shutil.which("python3") is None, reason="requires python3 on PATH")
def test_ownership_a_same_named_unmarked_package_is_never_judged(tmp_path: Path):
    """The `boot` collision: the NAME is not the ownership test.

    This package shares a name with a canonical one and its body differs
    wholesale, so a name-keyed comparison would call it stale on every run
    forever. It carries no CPP `metadata.source`, so it is not ours to judge.
    """
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_skills_checker(checkout)
    _make_canonical_skill(checkout)
    home = tmp_path / "home"
    _make_helpers(home)  # a host with CPP installed; otherwise the global skip fires
    _make_installed_skill(home, UNMARKED_SKILL)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["claude_skills_checked"] is True
    assert payload["claude_skills_managed"] == 0
    assert payload["claude_skills_stale"] == 0
    assert "none is ours to judge" in report.stdout


@pytest.mark.skipif(shutil.which("python3") is None, reason="requires python3 on PATH")
def test_blind_control_an_absent_checker_reports_not_checked_never_clean(
    tmp_path: Path,
):
    """Membership floor: a comparison that did not run must not read as clean."""
    checkout = _make_checkout(tmp_path / "checkout")
    _make_canonical_skill(checkout)  # deliberately NO skills-check.py in the checkout
    home = tmp_path / "home"
    _make_installed_skill(home, MANAGED_SKILL)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["claude_skills_checked"] is False
    assert payload["claude_skills_stale"] == 0
    assert "NOT CHECKED" in report.stdout
    assert "Unchecked is not clean" in report.stdout


@pytest.mark.skipif(shutil.which("python3") is None, reason="requires python3 on PATH")
def test_blind_control_an_unparseable_checker_reports_not_checked(tmp_path: Path):
    """A checker whose output format changed did not report zero findings."""
    checkout = _make_checkout(tmp_path / "checkout")
    stub = checkout / "scripts" / "skills-check.py"
    stub.parent.mkdir(parents=True, exist_ok=True)
    stub.write_text("print('some other shape entirely')\n", encoding="utf-8")
    _make_canonical_skill(checkout)
    home = tmp_path / "home"
    _make_installed_skill(home, MANAGED_SKILL)

    payload = json.loads(_run(checkout, home, "--json").stdout)
    assert payload["claude_skills_checked"] is False


def test_an_absent_claude_skills_root_is_reported_not_checked(tmp_path: Path):
    """No install root is a different answer from an install root with nothing."""
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_skills_checker(checkout)
    home = tmp_path / "home"
    _make_helpers(home)

    payload = json.loads(_run(checkout, home, "--json").stdout)
    assert payload["claude_skills_checked"] is False
    assert payload["claude_skills_managed"] == 0


# ---------------------------------------------------------------------------
# Job 5: checkout provenance (issue #1029, specimen 1)
# ---------------------------------------------------------------------------


def test_provenance_is_reported_and_is_never_a_fabricated_zero(tmp_path: Path):
    """Every job above compares against THE CHECKOUT and none can date it.

    With no provenance helper in the checkout, the field must say so rather than
    reporting a gap of zero - an unmeasured premise and a satisfied one are
    different facts, which is the whole of #1029.
    """
    checkout = _make_checkout(tmp_path / "checkout")
    home = tmp_path / "home"
    _make_helpers(home)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["toolchain_provenance"] == "unavailable"
    assert payload["toolchain_behind"] is None
    assert "NOT MEASURED" in report.stdout


def test_provenance_unknown_is_not_reported_as_current(tmp_path: Path):
    """A real helper over a non-repo checkout reports unknown, not a zero gap."""
    checkout = _make_checkout(tmp_path / "checkout")
    shutil.copy2(
        ROOT / "scripts" / "toolchain-provenance.sh",
        checkout / "scripts" / "toolchain-provenance.sh",
    )
    (checkout / "scripts" / "toolchain-provenance.sh").chmod(0o755)
    home = tmp_path / "home"
    _make_helpers(home)

    report = _run(checkout, home)
    payload = json.loads(_run(checkout, home, "--json").stdout)

    assert payload["toolchain_provenance"] == "unknown"
    assert payload["toolchain_behind"] is None
    assert "not a gap of zero" in report.stdout.lower()


@pytest.mark.skipif(shutil.which("python3") is None, reason="requires python3 on PATH")
def test_quiet_reports_an_unanswered_claude_skills_comparison(tmp_path: Path):
    """The quiet line is the one that reaches a session start.

    Report mode said NOT CHECKED and quiet said nothing at all, so a host whose
    checker was missing printed byte-identically to a clean host - the
    report-mode fix applied to one surface and not the one anybody reads
    (counter-model review, codex/gpt-6-astra).
    """
    checkout = _make_checkout(tmp_path / "checkout")  # deliberately no skills-check.py
    _make_canonical_skill(checkout)
    home = tmp_path / "home"
    _make_helpers(home)
    _make_installed_skill(home, MANAGED_SKILL)

    quiet = _run(checkout, home, "--quiet")
    assert "NOT checked" in quiet.stdout
    assert "unchecked, not clean" in quiet.stdout


@pytest.mark.skipif(shutil.which("python3") is None, reason="requires python3 on PATH")
def test_quiet_is_silent_when_the_claude_comparison_actually_ran(tmp_path: Path):
    """The negative half: the advisory must be a fact, not boilerplate.

    Without it, the fix above could have been an unconditional line, which is a
    line everyone learns to skip.
    """
    checkout = _make_checkout(tmp_path / "checkout")
    _install_real_skills_checker(checkout)
    _make_canonical_skill(checkout)
    home = tmp_path / "home"
    _make_helpers(home)
    _make_installed_skill(home, MANAGED_SKILL)

    quiet = _run(checkout, home, "--quiet")
    assert "NOT checked" not in quiet.stdout
    assert quiet.stdout.strip() == ""


def test_provenance_carries_its_own_qualification(tmp_path: Path):
    """The gap and the age of the evidence behind it are ONE fact.

    Emitting `current / 0` without the upstream and the evidence age let a
    checkout matching a ref last fetched months ago reach a consumer as current,
    which is the original failure with a number attached.
    """
    checkout = _make_checkout(tmp_path / "checkout")
    shutil.copy2(
        ROOT / "scripts" / "toolchain-provenance.sh",
        checkout / "scripts" / "toolchain-provenance.sh",
    )
    (checkout / "scripts" / "toolchain-provenance.sh").chmod(0o755)
    home = tmp_path / "home"
    _make_helpers(home)

    payload = json.loads(_run(checkout, home, "--json").stdout)
    for field in (
        "toolchain_provenance",
        "toolchain_behind",
        "toolchain_upstream",
        "toolchain_fetch_age_seconds",
        "toolchain_fetch_age_source",
    ):
        assert field in payload, field
    # Unmeasurable here, and every unmeasurable field must be null, not zero.
    assert payload["toolchain_behind"] is None
    assert payload["toolchain_upstream"] is None
    assert payload["toolchain_fetch_age_seconds"] is None
