from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

SCRIPT = Path(__file__).parents[1] / "scripts" / "check-claude-md-behavior.py"
SPEC = importlib.util.spec_from_file_location("check_claude_md_behavior", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
behavior = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = behavior
SPEC.loader.exec_module(behavior)


def _write_fixture(root: Path, *, needle: str = "never output secrets", retirements: object = None) -> None:
    fixture = root / behavior.FIXTURE
    fixture.parent.mkdir(parents=True, exist_ok=True)
    fixture.write_text(
        json.dumps(
            {
                "version": behavior.FIXTURE_VERSION,
                "obligations": [{"slug": "never-output-secrets", "needle": needle}],
                "retirements": {} if retirements is None else retirements,
            }
        ),
        encoding="utf-8",
    )


def test_obligation_can_move_to_docs(tmp_path: Path) -> None:
    (tmp_path / "CLAUDE.md").write_text("Read docs on demand.", encoding="utf-8")
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "safety.md").write_text("Never output secrets in responses.", encoding="utf-8")
    _write_fixture(tmp_path)

    assert behavior.check_tree(tmp_path) == []


def test_missing_obligation_fails(tmp_path: Path) -> None:
    (tmp_path / "CLAUDE.md").write_text("Short routing file.", encoding="utf-8")
    _write_fixture(tmp_path)
    assert "never output secrets" not in (tmp_path / "CLAUDE.md").read_text(encoding="utf-8").casefold()

    findings = behavior.check_tree(tmp_path)

    assert [(finding.kind, finding.detail) for finding in findings] == [
        ("missing-obligation", "never-output-secrets: expected findable text 'never output secrets'")
    ]


def test_named_retirement_allowlist_permits_deliberate_removal(tmp_path: Path) -> None:
    (tmp_path / "CLAUDE.md").write_text("Short routing file.", encoding="utf-8")
    _write_fixture(
        tmp_path,
        retirements={"never-output-secrets": "superseded by platform-level response redaction"},
    )
    assert "never output secrets" not in (tmp_path / "CLAUDE.md").read_text(encoding="utf-8").casefold()

    assert behavior.check_tree(tmp_path) == []


def test_bare_retirement_without_reason_fails(tmp_path: Path) -> None:
    (tmp_path / "CLAUDE.md").write_text("Short routing file.", encoding="utf-8")
    _write_fixture(tmp_path, retirements={"never-output-secrets": ""})

    findings = behavior.check_tree(tmp_path)

    assert findings[0].kind == "invalid-fixture"
    assert "requires a named reason" in findings[0].detail


def test_duplicated_normative_lifecycle_policy_in_skill_fails_locality_check(tmp_path: Path) -> None:
    (tmp_path / "CLAUDE.md").write_text("Never output secrets.", encoding="utf-8")
    _write_fixture(tmp_path)
    skill = tmp_path / ".claude" / "commands" / "flow" / "finish.md"
    skill.parent.mkdir(parents=True)
    skill.write_text(
        "# Finish\n\n| Knowledge in the completed spec | Durable home |\n|---|---|\n| behavior | tests |\n",
        encoding="utf-8",
    )
    assert behavior.NORMATIVE_TABLE_MARKER in skill.read_text(encoding="utf-8")

    findings = behavior.check_tree(tmp_path)

    assert [(finding.kind, finding.detail) for finding in findings] == [
        ("duplicated-lifecycle-policy", ".claude/commands/flow/finish.md")
    ]


def test_non_boundary_skill_cannot_link_canonical_lifecycle_reference(tmp_path: Path) -> None:
    (tmp_path / "CLAUDE.md").write_text("Never output secrets.", encoding="utf-8")
    _write_fixture(tmp_path)
    skill = tmp_path / ".claude" / "commands" / "security" / "scan.md"
    skill.parent.mkdir(parents=True)
    skill.write_text("See docs/agents/knowledge-lifecycle.md.\n", encoding="utf-8")
    assert skill.relative_to(tmp_path).as_posix() not in behavior.LIFECYCLE_BOUNDARY_FILES

    findings = behavior.check_tree(tmp_path)

    assert [(finding.kind, finding.detail) for finding in findings] == [
        ("non-boundary-lifecycle-pointer", ".claude/commands/security/scan.md")
    ]


# --- Verified generated documentation distribution (issue #861) --------------------
#
# The bundler copies a canonical document into a generated skill so the link a command
# body publishes still resolves in an installed skill. That copy is DISTRIBUTION of
# docs/, not a second policy - but the allowance has to be earned per file, or it is
# just an exemption for anything filed under a generated-looking path.
#
# These tests pin the shape of the allowance from both sides: the intended copies pass,
# and every way of not being an intended copy still fails.

LIFECYCLE_POLICY = (
    "# Knowledge lifecycle\n\n"
    f"{behavior.NORMATIVE_TABLE_MARKER}\n"
    "|---|---|\n"
    "| A rule | a behavioural test |\n"
)
GENERATED_MARKER = "<!-- GENERATED by claude-power-pack - scripts/codex-skill-sync.py; edit x instead -->"


def _distribution_repo(
    root: Path,
    *,
    managed: bool = True,
    canonical: bool = True,
    copy_text: str | None = None,
    with_bundler: bool = True,
) -> Path:
    """A repo with one generated skill carrying a copy of the lifecycle policy."""
    (root / "CLAUDE.md").write_text("Read docs on demand.", encoding="utf-8")
    _write_fixture(root)
    docs = root / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "safety.md").write_text("Never output secrets in responses.", encoding="utf-8")
    if canonical:
        (docs / "agents").mkdir(parents=True, exist_ok=True)
        (docs / "agents" / "knowledge-lifecycle.md").write_text(
            LIFECYCLE_POLICY, encoding="utf-8"
        )

    skill = root / "codex" / "skills" / "flow-auto"
    (skill / "docs" / "agents").mkdir(parents=True, exist_ok=True)
    (skill / "SKILL.md").write_text(
        (GENERATED_MARKER if managed else "# Hand written skill") + "\n\nBody.\n",
        encoding="utf-8",
    )
    (skill / "docs" / "agents" / "knowledge-lifecycle.md").write_text(
        LIFECYCLE_POLICY if copy_text is None else copy_text, encoding="utf-8"
    )

    if with_bundler:
        scripts = root / "scripts"
        scripts.mkdir(exist_ok=True)
        # The REAL bundler, so `is_managed` is the same predicate that writes the files.
        real = Path(__file__).parents[1] / "scripts" / "codex-skill-sync.py"
        (scripts / "codex-skill-sync.py").write_text(
            real.read_text(encoding="utf-8"), encoding="utf-8"
        )
    return skill


def _kinds(root: Path) -> list[str]:
    return [f.kind for f in behavior.check_tree(root)]


def test_a_verified_generated_copy_is_distribution_not_a_second_policy(tmp_path) -> None:
    _distribution_repo(tmp_path)

    assert _kinds(tmp_path) == []


def test_an_altered_generated_copy_is_still_reported(tmp_path) -> None:
    """The whole point of verifying: a copy that drifted is no longer a copy."""
    _distribution_repo(tmp_path, copy_text=LIFECYCLE_POLICY + "\nLocally edited.\n")

    assert "duplicated-lifecycle-policy" in _kinds(tmp_path)


def test_a_copy_in_an_unmanaged_skill_is_still_reported(tmp_path) -> None:
    """A hand-curated skill dir is authored content, whatever it is filed under."""
    _distribution_repo(tmp_path, managed=False)

    assert "duplicated-lifecycle-policy" in _kinds(tmp_path)


def test_a_copy_with_no_canonical_source_is_still_reported(tmp_path) -> None:
    """Provenance case: nothing upstream owns this, so it is not distribution."""
    _distribution_repo(tmp_path, canonical=False)

    assert "duplicated-lifecycle-policy" in _kinds(tmp_path)


def test_the_allowance_fails_closed_without_the_bundler(tmp_path) -> None:
    """Unverifiable is reported, never waved through."""
    _distribution_repo(tmp_path, with_bundler=False)

    assert "duplicated-lifecycle-policy" in _kinds(tmp_path)


def test_policy_pasted_into_a_generated_command_body_is_still_reported(tmp_path) -> None:
    """The allowance covers <skill>/docs/ only - never the command body itself."""
    skill = _distribution_repo(tmp_path)
    (skill / "reference.md").write_text(LIFECYCLE_POLICY, encoding="utf-8")

    findings = [f for f in behavior.check_tree(tmp_path) if "reference.md" in f.detail]

    assert [f.kind for f in findings] == ["duplicated-lifecycle-policy"]


def test_the_real_repo_bundled_docs_are_recognised_as_distribution(tmp_path) -> None:
    """Against the actual tree, not a fixture: the shipped copies must pass.

    Paired with the failure cases above, this is what distinguishes a working
    allowance from a check that stopped looking at codex/skills entirely.
    """
    root = Path(__file__).parents[1]
    bundled = sorted((root / "codex" / "skills").glob("*/docs/**/*.md"))
    assert bundled, "no bundled docs found; this pin is stale"
    is_managed = behavior._bundler_is_managed(root)
    assert is_managed is not None, "the bundler could not be imported"

    unverified = [
        str(path.relative_to(root))
        for path in bundled
        if not behavior.is_verified_generated_doc(path, root, is_managed)
    ]

    assert not unverified, "shipped copies not recognised as distribution: " + ", ".join(unverified)
