"""Regression tests for skill drift/orphan detection (issue #395).

The core hazard: every CPP-generated skill references a manifests/ source that
no longer exists, so a repo-presence prune would delete live skills. These tests
pin the curated-list-only classifier and the prune guardrails.
"""

from __future__ import annotations

import importlib.util
import json
import stat
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "skill-drift.py"

_spec = importlib.util.spec_from_file_location("skill_drift", SCRIPT)
assert _spec and _spec.loader
sd = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sd)

GEN = "<!-- GENERATED by claude-power-pack -->"


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def _make_skill(skills_dir: Path, name: str, family: str | None, generated: bool = True) -> None:
    d = skills_dir / name
    d.mkdir(parents=True)
    header = f"{GEN}\n" if generated else "hand authored\n"
    fam = f"metadata:\n  family: {family}\n" if family else ""
    (d / "SKILL.md").write_text(header + fam, encoding="utf-8")


def _depfile(tmp_path: Path, body: str) -> Path:
    f = tmp_path / "deprecated-skills.yaml"
    f.write_text(textwrap.dedent(body), encoding="utf-8")
    return f


def _status(findings: list[dict], skill: str) -> str:
    return next(f["status"] for f in findings if f["skill"] == skill)


DEPRECATION = """\
    version: 1
    deprecated:
      - family: wiki
        entire_family: true
        reason: Wiki.js retired
        replacement: GitHub Issues
        skills:
          - wiki-search
          - wiki-create-page
      - family: flow
        reason: one flow skill retired, family still live
        skills:
          - flow-legacy
"""


# --------------------------------------------------------------------------- #
# Classification
# --------------------------------------------------------------------------- #
def test_classify_statuses(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "wiki-search", "wiki")          # explicit -> DEPRECATED
    _make_skill(skills, "wiki-export", "wiki")          # stray in retired family -> ORPHANED
    _make_skill(skills, "flow-auto", "flow")            # live (flow not entire_family) -> OK
    _make_skill(skills, "grill-me", "grill")            # unlisted family -> OK
    _make_skill(skills, "my-custom", "custom", generated=False)  # no marker -> IGNORED
    (skills / "leftover").mkdir()                       # no SKILL.md -> IGNORED

    findings = sd.classify(skills, _depfile(tmp_path, DEPRECATION))

    assert _status(findings, "wiki-search") == sd.DEPRECATED
    assert _status(findings, "wiki-export") == sd.ORPHANED
    assert _status(findings, "flow-auto") == sd.OK
    assert _status(findings, "grill-me") == sd.OK
    assert _status(findings, "my-custom") == sd.IGNORED
    assert _status(findings, "leftover") == sd.IGNORED


def test_partial_family_does_not_orphan_live_skills(tmp_path: Path) -> None:
    """Bug A: a not-fully-retired family must never orphan its live members."""
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "flow-auto", "flow")
    _make_skill(skills, "flow-start", "flow")
    findings = sd.classify(skills, _depfile(tmp_path, DEPRECATION))
    assert _status(findings, "flow-auto") == sd.OK
    assert _status(findings, "flow-start") == sd.OK


def test_no_deprecation_file_keeps_everything_ok(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "wiki-search", "wiki")
    findings = sd.classify(skills, tmp_path / "missing.yaml")
    assert _status(findings, "wiki-search") == sd.OK
    assert sd.removable(findings) == []


# --------------------------------------------------------------------------- #
# Prune guardrails
# --------------------------------------------------------------------------- #
def test_prune_moves_deprecated_to_backup(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "wiki-search", "wiki")
    backup = tmp_path / "backup"
    findings = sd.classify(skills, _depfile(tmp_path, DEPRECATION))

    rc = sd.prune(["wiki-search"], skills, backup, findings)

    assert rc == 0
    assert not (skills / "wiki-search").exists()
    moved = list(backup.rglob("wiki-search/SKILL.md"))
    assert len(moved) == 1  # preserved in backup, not destroyed


def test_prune_refuses_ok_skill(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "flow-auto", "flow")
    findings = sd.classify(skills, _depfile(tmp_path, DEPRECATION))
    rc = sd.prune(["flow-auto"], skills, tmp_path / "backup", findings)
    assert rc == 1
    assert (skills / "flow-auto").exists()  # untouched


def test_prune_refuses_hand_authored(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "my-custom", "custom", generated=False)
    findings = sd.classify(skills, _depfile(tmp_path, DEPRECATION))
    rc = sd.prune(["my-custom"], skills, tmp_path / "backup", findings)
    assert rc == 1
    assert (skills / "my-custom").exists()


def test_prune_refuses_symlinked_entry(tmp_path: Path) -> None:
    """A symlink to a live sibling must never have its target moved."""
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "flow-auto", "flow")            # live target
    (skills / "wiki-search").symlink_to(skills / "flow-auto")  # masquerades as deprecated
    findings = sd.classify(skills, _depfile(tmp_path, DEPRECATION))
    rc = sd.prune(["wiki-search"], skills, tmp_path / "backup", findings)
    assert rc == 1
    assert (skills / "flow-auto").is_dir()  # real target untouched


def test_read_family_strips_quotes(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    d = skills / "wiki-export"
    d.mkdir()
    (d / "SKILL.md").write_text(f'{GEN}\nmetadata:\n  family: "wiki"\n', encoding="utf-8")
    findings = sd.classify(skills, _depfile(tmp_path, DEPRECATION))
    # quoted family must still resolve to the retired family -> ORPHANED, not OK
    assert _status(findings, "wiki-export") == sd.ORPHANED


def test_prune_refuses_path_traversal(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "wiki-search", "wiki")
    secret = tmp_path / "secret"
    secret.mkdir()
    findings = sd.classify(skills, _depfile(tmp_path, DEPRECATION))
    for bad in ("../secret", "../../etc", "..", "."):
        rc = sd.prune([bad], skills, tmp_path / "backup", findings)
        assert rc == 1
    assert secret.exists()


# --------------------------------------------------------------------------- #
# Fallback YAML parser parity
# --------------------------------------------------------------------------- #
def test_fallback_parser_matches_real_file() -> None:
    real = (ROOT / ".claude" / "deprecated-skills.yaml").read_text(encoding="utf-8")
    import yaml

    expected = yaml.safe_load(real)
    got = sd._fallback_parse(real)

    exp_fams = {f["family"]: f for f in expected["deprecated"]}
    got_fams = {f["family"]: f for f in got["deprecated"]}
    assert set(exp_fams) == set(got_fams)
    for fam, ef in exp_fams.items():
        gf = got_fams[fam]
        assert sorted(gf.get("skills", [])) == sorted(ef.get("skills", []))
        assert bool(gf.get("entire_family")) == bool(ef.get("entire_family"))


# --------------------------------------------------------------------------- #
# CLI contract
# --------------------------------------------------------------------------- #
def _run(args: list[str], tmp_path: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        cwd=ROOT, text=True, capture_output=True, check=False,
    )


def test_cli_check_exit_codes(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "flow-auto", "flow")
    dep = _depfile(tmp_path, DEPRECATION)

    clean = _run(["--check", "--skills-dir", str(skills), "--deprecated-file", str(dep)], tmp_path)
    assert clean.returncode == 0
    assert "No deprecated or orphaned skills" in clean.stdout

    _make_skill(skills, "wiki-search", "wiki")
    drift = _run(["--check", "--skills-dir", str(skills), "--deprecated-file", str(dep)], tmp_path)
    assert drift.returncode == 1
    assert "DEPRECATED" in drift.stdout


def test_cli_json_shape(tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    skills.mkdir()
    _make_skill(skills, "wiki-search", "wiki")
    dep = _depfile(tmp_path, DEPRECATION)
    res = _run(["--json", "--skills-dir", str(skills), "--deprecated-file", str(dep)], tmp_path)
    data = json.loads(res.stdout)
    rec = next(f for f in data if f["skill"] == "wiki-search")
    assert set(rec) == {"skill", "family", "status", "reason", "replacement"}
    assert rec["status"] == sd.DEPRECATED
    assert res.returncode == 1


def test_script_is_executable() -> None:
    assert SCRIPT.stat().st_mode & stat.S_IXUSR
