#!/usr/bin/env python3
"""codex-prompt-sync.py - single-source -> per-harness generation for Codex CLI.

Issue #446 (epic #417 Phase C): make surviving CPP command families consumable
from Codex CLI off the same single source Claude Code uses. ADR 0001 section 5
fixes the source of truth as .claude/commands/<family>/*.md; this script emits
the Codex-harness artifacts as checked-in custom prompts under codex/prompts/
(<family>-<command>.md -> Codex `/<family>-<command>`), replacing the retired
scripts/codex-skill-gen.py wrapper generator.

DEPRECATED (issue #555): this flat custom-prompt surface is superseded by the
per-command Codex skills emitted by scripts/codex-skill-sync.py under
codex/skills/. Both surfaces stay generated and drift-checked until the
codex-power-pack cutover (issue #556) retires codex/prompts/. New harness
transforms belong in the skill generator, not here.

    codex-prompt-sync.py                      # --check (default): exit 1 on drift
    codex-prompt-sync.py --check [family...]  # check some or all families
    codex-prompt-sync.py --write [family...]  # (re)generate codex/prompts/
    codex-prompt-sync.py --install            # copy codex/prompts/*.md -> ~/.codex/prompts/

Ownership rule: the script manages ONLY files carrying its GENERATED marker.
Hand-curated prompts (codex/prompts/cpp-memory.md) are never overwritten or
orphan-deleted. Mirrors the plugin-sync.sh idioms: deterministic, git-free
(byte-for-byte local diff, no network) so it runs in the git-less CI validate
container. Reconcile drift by editing the SOURCE (.claude/commands/<family>/)
then re-running with --write.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_ROOT = REPO_ROOT / ".claude" / "commands"
OUTPUT_ROOT = REPO_ROOT / "codex" / "prompts"

# Same packaged families as plugin-sync.sh (ADR 0001 target design), minus the
# `codex` family: those commands orchestrate the Codex CLI itself, so shipping
# them INTO Codex as prompts would be circular.
FAMILIES = [
    "browser", "cicd", "claude-md", "cpp", "documentation", "evaluate",
    "flow", "github", "project", "qa", "second-opinion", "secrets",
    "security", "self-improvement",
]

# Per-family source basenames excluded from generation.
#   cpp: the legacy symlink installer retires in Phase B4 (mirror plugin-sync).
#   self-improvement/memory.md: Codex ships the hand-curated equivalent
#     codex/prompts/cpp-memory.md (issue #433); generating a second variant
#     would duplicate the surface.
EXCLUDE: dict[str, set[str]] = {
    "cpp": {"init.md", "status.md", "update.md"},
    "self-improvement": {"memory.md"},
}

MARKER_PREFIX = (
    "<!-- GENERATED by claude-power-pack - scripts/codex-prompt-sync.py;"
)

# Claude-only surfaces: when a command body references any of these, the
# generated prompt gets a harness note telling Codex to use script/CLI
# fallbacks (adapted from the retired codex-skill-gen.py indicator list).
CLAUDE_ONLY_INDICATORS = [
    "EnterWorktree", "ExitWorktree", "AskUserQuestion", "Skill tool",
    "mcp__", "MCP", "playwright", "second-opinion",
]

HARNESS_NOTE = (
    "> **Codex harness note:** generated from a Claude Code command. Where it\n"
    "> references Claude-only surfaces (MCP tools, `Skill`/`EnterWorktree` tool\n"
    "> calls, or slash commands not installed as Codex prompts), fall back to the\n"
    "> referenced repo scripts and CLI entry points, or inspect the implementation\n"
    "> directly. Relative paths like `scripts/...` resolve against the\n"
    "> claude-power-pack checkout.\n"
)


def marker_for(family: str, base: str) -> str:
    return (
        f"{MARKER_PREFIX} edit .claude/commands/{family}/{base} instead -->"
    )


def strip_frontmatter(content: str) -> str:
    """Drop a leading YAML frontmatter block (Codex prompts are plain markdown)."""
    if not content.startswith("---"):
        return content
    end = content.find("\n---", 3)
    if end == -1:
        return content
    return content[end + len("\n---"):].lstrip("\n")


def generated_names(selected: list[str]) -> dict[tuple[str, str], str]:
    """Map (family, stem) -> output basename for every command being generated."""
    names: dict[tuple[str, str], str] = {}
    for family in selected:
        src_dir = SOURCE_ROOT / family
        if not src_dir.is_dir():
            raise FileNotFoundError(f"source dir not found: {src_dir}")
        for f in sorted(src_dir.glob("*.md")):
            if f.name in EXCLUDE.get(family, set()):
                continue
            names[(family, f.stem)] = f"{family}-{f.stem}.md"
    return names


_SLASH_REF = re.compile(r"/([a-z][a-z0-9-]*):([a-z][a-z0-9-]*)")


def rewrite_slash_refs(body: str, names: dict[tuple[str, str], str]) -> str:
    """Rewrite /family:cmd -> /family-cmd, only for refs that resolve to a
    generated prompt; unknown targets (e.g. /codex:auto, /cpp:init) are left
    untouched so the harness note covers them."""

    def repl(match: re.Match[str]) -> str:
        family, stem = match.group(1), match.group(2)
        if (family, stem) in names:
            return f"/{family}-{stem}"
        return match.group(0)

    return _SLASH_REF.sub(repl, body)


def generate_prompt(
    source_file: Path, family: str, names: dict[tuple[str, str], str]
) -> str:
    body = strip_frontmatter(source_file.read_text())
    body = rewrite_slash_refs(body, names)
    note = ""
    if any(ind in body for ind in CLAUDE_ONLY_INDICATORS):
        note = HARNESS_NOTE + "\n"
    return f"{marker_for(family, source_file.name)}\n\n{note}{body.rstrip()}\n"


def expected_outputs(selected: list[str]) -> dict[str, str]:
    """Map output basename -> expected content for the selected families.

    The rewrite map always spans ALL families so cross-family refs resolve
    identically no matter which subset is being synced.
    """
    all_names = generated_names(FAMILIES)
    outputs: dict[str, str] = {}
    for family in selected:
        src_dir = SOURCE_ROOT / family
        for f in sorted(src_dir.glob("*.md")):
            if f.name in EXCLUDE.get(family, set()):
                continue
            outputs[f"{family}-{f.stem}.md"] = generate_prompt(f, family, all_names)
    return outputs


def is_managed(path: Path) -> bool:
    try:
        with path.open() as fh:
            return fh.readline().startswith(MARKER_PREFIX)
    except OSError:
        return False


def find_orphans(outputs: dict[str, str], selected: list[str]) -> list[Path]:
    """Marker-bearing files under codex/prompts/ with no matching source.

    Only families in `selected` are considered so a partial-family run never
    misreads other families' outputs as orphans.
    """
    prefixes = tuple(f"{family}-" for family in selected)
    orphans = []
    for f in sorted(OUTPUT_ROOT.glob("*.md")):
        if f.name in outputs or not f.name.startswith(prefixes):
            continue
        if is_managed(f):
            orphans.append(f)
    return orphans


def run_check(selected: list[str]) -> int:
    outputs = expected_outputs(selected)
    drift = 0
    for base, content in outputs.items():
        dest = OUTPUT_ROOT / base
        if not dest.is_file():
            print(f"MISSING prompt: codex/prompts/{base}")
            drift = 1
        elif dest.read_text() != content:
            print(f"DRIFT: codex/prompts/{base} differs from generated source")
            drift = 1
    for orphan in find_orphans(outputs, selected):
        print(f"ORPHAN prompt: codex/prompts/{orphan.name} (no matching source command)")
        drift = 1
    if drift:
        print(
            "\ncodex-prompt-sync: DRIFT detected. Edit the SOURCE"
            " (.claude/commands/<family>/), then run:"
            " scripts/codex-prompt-sync.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"codex-prompt-sync: {len(outputs)} prompt(s) in sync ({', '.join(selected)})")
    return 0


def run_write(selected: list[str]) -> int:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    outputs = expected_outputs(selected)
    written = 0
    for base, content in outputs.items():
        dest = OUTPUT_ROOT / base
        if not dest.is_file() or dest.read_text() != content:
            dest.write_text(content)
            written += 1
    removed = 0
    for orphan in find_orphans(outputs, selected):
        orphan.unlink()
        print(f"codex-prompt-sync: removed orphan {orphan.name}")
        removed += 1
    print(
        f"codex-prompt-sync: {len(outputs)} prompt(s) current"
        f" ({written} written, {removed} orphan(s) removed)"
    )
    return 0


def run_install() -> int:
    if not OUTPUT_ROOT.is_dir():
        print(f"codex-prompt-sync: nothing to install ({OUTPUT_ROOT} missing)", file=sys.stderr)
        return 2
    dest_dir = Path.home() / ".codex" / "prompts"
    dest_dir.mkdir(parents=True, exist_ok=True)
    count = 0
    for f in sorted(OUTPUT_ROOT.glob("*.md")):
        shutil.copyfile(f, dest_dir / f.name)
        count += 1
    print(f"codex-prompt-sync: installed {count} prompt(s) -> {dest_dir}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Codex CLI prompts from .claude/commands/<family>/ sources"
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail on drift (default)")
    mode.add_argument("--write", action="store_true", help="(re)generate codex/prompts/")
    parser.add_argument(
        "--install", action="store_true",
        help="copy codex/prompts/*.md (generated + curated) to ~/.codex/prompts/",
    )
    parser.add_argument("families", nargs="*", help="subset of families (default: all)")
    args = parser.parse_args(argv)

    selected = args.families or FAMILIES
    for family in selected:
        if family not in FAMILIES:
            print(
                f"codex-prompt-sync: unknown family '{family}'"
                f" (known: {' '.join(FAMILIES)})",
                file=sys.stderr,
            )
            return 2

    if args.write:
        rc = run_write(selected)
    elif args.install and not args.check:
        rc = 0  # install-only invocation
    else:
        rc = run_check(selected)

    if rc == 0 and args.install:
        rc = run_install()
    return rc


if __name__ == "__main__":
    sys.exit(main())
