name: Bug Report
description: Report a bug in the MCP server, commands, or skills
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Found a bug? Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of claude-power-pack is affected?
      options:
        - MCP Second Opinion server
        - Slash command
        - Skill
        - Hook
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: specific
    attributes:
      label: Specific item
      description: Which command, skill, or tool?
      placeholder: "e.g., /django:init, best-practices skill, get_second_opinion tool"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What happened? What did you expect to happen?
      placeholder: |
        **What happened:**
        [describe the bug]

        **Expected behavior:**
        [what should have happened]
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Run command '...'
        2. Enter '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error message
      description: If there's an error message, paste it here
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your setup details
      value: |
        - OS:
        - Claude Code version:
        - Python version (if MCP):
        - Node version (if applicable):
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information that might help
    validations:
      required: false
