#!/bin/bash
# Bootstrap a dedicated Woodpecker CI agent host.
#
# Run ON the target box as the operator user (needs passwordless sudo):
#
#   WOODPECKER_SERVER=<woodpecker-server-host>:9001 \
#   WOODPECKER_AGENT_SECRET=... \
#   WOODPECKER_AGENT_LABELS=host=ci \
#   bash bootstrap-agent-host.sh
#
# Or from a machine that can SSH to it (secret travels on stdin into the
# remote environment - never on argv, never in output):
#
#   scp woodpecker/bootstrap-agent-host.sh <user>@<agent-host>:~/
#   ssh <user>@<agent-host> 'export WOODPECKER_AGENT_SECRET="$(cat)"; \
#     WOODPECKER_SERVER=<woodpecker-server-host>:9001 WOODPECKER_AGENT_LABELS=host=ci \
#     bash ~/bootstrap-agent-host.sh' \
#     < <(grep '^WOODPECKER_AGENT_SECRET=' woodpecker/agent.env | cut -d= -f2-)
#
# WOODPECKER_SERVER must be the server's *gRPC* endpoint. Our server compose
# maps 9001:9000 (gRPC) and 9000:8000 (HTTP), so it is <server>:9001.
#
# The box holds no project secrets: only the agent secret, and the
# deploy SSH key stays a Woodpecker *server* secret materialised inside the
# ephemeral deploy container.
set -euo pipefail

: "${WOODPECKER_SERVER:?set WOODPECKER_SERVER to the gRPC endpoint, e.g. woodpecker.internal:9001}"
: "${WOODPECKER_AGENT_SECRET:?set WOODPECKER_AGENT_SECRET}"
WOODPECKER_AGENT_LABELS=${WOODPECKER_AGENT_LABELS:-host=$(hostname -s)}
WOODPECKER_MAX_WORKFLOWS=${WOODPECKER_MAX_WORKFLOWS:-2}
AGENT_IMAGE=${AGENT_IMAGE:-woodpeckerci/woodpecker-agent:v3.13.0@sha256:a983b1016217ad94cdab48d732ec97b5b1f72718725d651183d7ec885f7caf35}
AGENT_DIR=${AGENT_DIR:-$HOME/woodpecker}

log() { printf '\n=== %s ===\n' "$*"; }

log "Packages (docker, compose v2, guest agent)"
if ! command -v docker >/dev/null; then
    sudo apt-get update -qq
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
        docker.io docker-compose-v2 qemu-guest-agent ca-certificates curl
fi
sudo systemctl enable --now docker qemu-guest-agent >/dev/null
if ! id -nG "$USER" | grep -qw docker; then
    sudo usermod -aG docker "$USER"
fi
# Run docker as the docker group for the rest of this script without re-login.
docker() { sg docker -c "docker $*"; }

log "Agent config in $AGENT_DIR"
mkdir -p "$AGENT_DIR"
# The secret file is REPLACED, never truncated in place: `umask 077` governs
# file CREATION, so a rerun over an existing mode-0644 agent.env would write the
# agent secret into a world-readable inode and the umask would not stop it.
# Create a fresh 0600 file and rename it over the old one.
umask 077
agent_env_tmp="$(mktemp "$AGENT_DIR/.agent.env.XXXXXX")"
chmod 600 "$agent_env_tmp"
cat > "$agent_env_tmp" <<EOF
WOODPECKER_SERVER=$WOODPECKER_SERVER
WOODPECKER_AGENT_SECRET=$WOODPECKER_AGENT_SECRET
EOF
mv -f "$agent_env_tmp" "$AGENT_DIR/agent.env"
umask 022
cat > "$AGENT_DIR/docker-compose.agent.yml" <<EOF
# Woodpecker CI agent - dedicated CI host. Generated by bootstrap-agent-host.sh.
services:
  woodpecker-agent:
    image: $AGENT_IMAGE
    container_name: woodpecker-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Persists the server-assigned agent id across restarts; without it
      # every restart registers a brand-new agent on the server.
      - ./agent-config:/etc/woodpecker
    env_file: agent.env
    environment:
      - WOODPECKER_MAX_WORKFLOWS=$WOODPECKER_MAX_WORKFLOWS
      - WOODPECKER_AGENT_LABELS=$WOODPECKER_AGENT_LABELS
      - WOODPECKER_HOSTNAME=$(hostname -s)
      - WOODPECKER_BACKEND=docker
${WOODPECKER_FILTER_LABELS:+      # Only take workflows whose labels match (dedicated host).
      - WOODPECKER_FILTER_LABELS=$WOODPECKER_FILTER_LABELS}
    restart: unless-stopped
EOF

log "Reachability: $WOODPECKER_SERVER"
host=${WOODPECKER_SERVER%%:*}; port=${WOODPECKER_SERVER##*:}
timeout 5 bash -c "</dev/tcp/$host/$port" && echo "gRPC port open" || { echo "cannot reach $WOODPECKER_SERVER"; exit 1; }

log "Start agent"
( cd "$AGENT_DIR" && docker compose -f docker-compose.agent.yml up -d )
sleep 5
docker logs --tail 20 woodpecker-agent 2>&1 | grep -v -i secret || true

log "Weekly image prune (keeps 7 days)"
# Both failure-tolerant clauses are load-bearing under `set -euo pipefail`:
# `crontab -l` exits 1 when no crontab exists (every first run) and `grep -v`
# exits 1 when it selects nothing (every run where the prune entry is the only
# line). Either killed the subshell before the echo, so `crontab -` was handed
# EMPTY INPUT and replaced the user's crontab with nothing. Build the new
# content first, and install it only once it is known to be non-empty.
# REPLACE OUR OWN ENTRY, not every line that mentions the same command. A
# `grep -v 'docker system prune'` filter cannot tell this script's job from an
# independently configured one on a different schedule, so a rerun silently
# deleted the operator's - "our thing changed" versus "a neighbour's", in a
# filter (counter-model review pass 2). The marker is what makes ours
# identifiable; anything without it is somebody else's and is preserved.
prune_marker='# woodpecker-bootstrap-agent-host: weekly image prune'
prune_entry="17 4 * * 0 docker system prune -af --filter until=168h >/dev/null 2>&1 $prune_marker"
existing_crontab="$(crontab -l 2>/dev/null || true)"
kept_crontab="$(printf '%s\n' "$existing_crontab" | grep -vF "$prune_marker" || true)"
new_crontab="$(printf '%s\n%s\n' "$kept_crontab" "$prune_entry" | sed '/^$/d')"
if [ -n "$new_crontab" ]; then
    printf '%s\n' "$new_crontab" | crontab -
else
    echo "refusing to install an empty crontab" >&2
fi

log "Done"
echo "hostname=$(hostname -s) labels=$WOODPECKER_AGENT_LABELS max_workflows=$WOODPECKER_MAX_WORKFLOWS server=$WOODPECKER_SERVER"
echo "Verify on the server side: woodpecker-cli agent ls  (expect $(hostname -s) online)"
