#!/usr/bin/env python3
"""BLIND ANCHOR for controls/dependency-audit (issue #961). NOT a gate.

CONSTRUCTED, not historical. `scripts/dependency-audit.py` is introduced by its
own pull request, so there is no earlier blind version of it anywhere in main's
history to vendor; the honest "before" is no check at all, which cannot be run
against a case. ADR 0008 ruled this shape acceptable for exactly this ticket -
"an anchor for a BRAND NEW gate cannot be historical on main, and that is
accepted rather than worked around... Integrity is established; historicity is
not."

WHAT THIS IS. The plausible weaker gate someone writes when the goal is stated
as "wire pip-audit into CI": confirm the audit produced a report, and treat that
as coverage. It is not a strawman - it is the shape the existing
`lib/security/modules/pip_audit.py` adapter already has one door down, where an
absent binary appends to `skipped` and the scan passes, and where a JSON parse
failure on a zero exit returns silently. "The step ran" reads as "we are
covered" until someone checks.

WHAT IT IS BLIND TO. It never looks inside `vulns`, and it never reads the
allowlist. So it misses all three known-bad inputs - an unaccounted advisory, a
suppression that suppresses nothing, and a deferral leaking onto a file it does
not name - and it agrees with the real gate on the known-good one, which is what
makes the demonstration isolated rather than an artifact of two programs
disagreeing generally.

Do not edit this file to satisfy a linter or a refactor. Its sha256 in
control.json is the integrity claim, and a byte that moves breaks it.
"""

from __future__ import annotations

import argparse
import json
import sys


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--allow-file", default=None)
    parser.add_argument("--from-capture", default=None)
    parser.add_argument("--capture", default=None)
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if not args.from_capture:
        print("DEP-AUDIT-UNKNOWN: this anchor only replays a capture", file=sys.stderr)
        return 2
    try:
        with open(args.from_capture, encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"DEP-AUDIT-UNKNOWN: capture unreadable: {exc}", file=sys.stderr)
        return 2

    files = payload.get("files") or []
    packages = 0
    for entry in files:
        report = entry.get("report") or {}
        # The whole of the blindness: the audit ran and its report parses, so
        # the dependency set is treated as covered. `vulns` is never read.
        deps = report.get("dependencies")
        if not isinstance(deps, list):
            print(f"DEP-AUDIT-UNKNOWN: {entry.get('path')} carries no report", file=sys.stderr)
            return 2
        packages += len(deps)

    print(
        f"dependency-audit: ok - {len(files)} file(s) examined (source=capture), "
        f"{packages} package(s) audited"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
