#!/usr/bin/env python3
"""flow-skill-sync.py - Regenerate the global flow-* skill mirror from repo commands.

Part of Claude Power Pack (CPP). Companion to scripts/skill-drift.py (which
detects *removal* drift against the deprecation list) - this script detects and
fixes *content* drift between the repo source of truth and the installed mirror.

Background
----------
CPP keeps two surfaces for the /flow workflow:

  * Source of truth : <repo>/.claude/commands/flow/<name>.md   (edited by PRs)
  * Global mirror   : ~/.claude/skills/flow-<name>/SKILL.md    (what EXECUTES
                       when a flow skill is invoked)

The manifest-driven generator that once produced the mirror was retired, so the
mirror became hand-maintained and silently drifted: PR #453 rebased the repo
commands onto native worktrees (EnterWorktree/ExitWorktree) but left the mirror
on the old manual `git worktree add` sibling-dir mechanics, still referencing a
retired Plane backend. This script closes that gap and guards against recurrence
(issue #457).

Each generated SKILL.md is: the CPP `GENERATED` marker, skill frontmatter
(name/description/argument-hint/metadata), then the VERBATIM body of the repo
command (its own leading frontmatter, if any, stripped). The frontmatter records
`source` (the repo command path) and `source_sha256` (a hash of the source file),
so drift is a one-line comparison: recompute the source hash and check it against
what the installed skill recorded.

Usage
-----
  flow-skill-sync.py                 # --check (report drift; exit 1 if any)
  flow-skill-sync.py --check         # explicit
  flow-skill-sync.py --write         # (re)generate the mirror from repo commands
  flow-skill-sync.py --json          # machine-readable drift findings
  flow-skill-sync.py --help

Options
  --skills-dir DIR    Mirror location (default: ~/.claude/skills)
  --commands-dir DIR  Source commands (default: <repo>/.claude/commands/flow)

Exit codes
  0 - No drift (--check), or write succeeded
  1 - Drift detected (--check/--json), or write failed
  2 - Usage / environment error
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# Detection substring shared with scripts/skill-drift.py (is_generated). A single
# dash is used deliberately: this file is repo-tracked and CLAUDE.md forbids em
# dashes. The marker also names the real source so a maintainer who opens the
# generated file knows not to hand-edit it.
MARKER_PREFIX = "GENERATED by claude-power-pack"


def _marker(name: str) -> str:
    return (
        f"<!-- {MARKER_PREFIX} - scripts/flow-skill-sync.py; "
        f"edit .claude/commands/flow/{name}.md instead -->"
    )


# The flow commands mirrored globally, with the skill metadata the mirror needs.
# `help` is intentionally excluded: it has no global mirror today and is an
# in-repo overview (/flow:help), not part of the executable loop. Descriptions
# are authored to match CURRENT repo behavior (native worktrees, GitHub-only, no
# grill-yourself/second-opinion/Plane) so the mirror's summary is truthful.
SKILLS: list[dict] = [
    {
        "cmd": "auto",
        "order": 10,
        "argument_hint": "/flow:auto",
        "description": (
            "Complete end-to-end lifecycle for a single issue: start worktree -> "
            "analyze -> ELI5 plan + necessity gate -> implement -> update docs -> "
            "finish (quality gates + PR) -> merge -> verify CI -> deploy. Rides "
            "Claude Code native worktrees. The one command to ship."
        ),
    },
    {
        "cmd": "start",
        "order": 20,
        "argument_hint": "/flow:start",
        "description": (
            "Create and enter a native worktree (.claude/worktrees/<name>) on an "
            "issue-anchored branch for a GitHub issue. Stateless - all context "
            "comes from git and GitHub. First step of the issue-driven loop."
        ),
    },
    {
        "cmd": "eli5",
        "order": 25,
        "argument_hint": "/flow:eli5 <ISSUE>",
        "description": (
            "Post-analysis, pre-implementation reviewer gate. Restates a GitHub "
            "issue's intent in plain language, gives a necessity/staleness verdict "
            "(Still needed / Partially addressed / No longer needed / Needs "
            "reframing) backed by evidence from work merged since the issue was "
            "filed, and presents the proposed changes for approval before any code "
            "is written."
        ),
    },
    {
        "cmd": "check",
        "order": 30,
        "argument_hint": "/flow:check",
        "description": (
            "Run local quality gates without committing: lint, tests, security "
            "scan, Makefile completeness, and an ignored-additions guard. Read-only "
            "pre-flight validation before /flow:finish."
        ),
    },
    {
        "cmd": "sync",
        "order": 40,
        "argument_hint": "/flow:sync",
        "description": (
            "Push the current worktree's branch to the remote so work can resume "
            "on another machine. Auto-commits any WIP as a squash-safe wip commit. "
            "Optional feature - most loops do not need it."
        ),
    },
    {
        "cmd": "finish",
        "order": 50,
        "argument_hint": "/flow:finish",
        "description": (
            "Run quality gates via the deterministic runner (lint, test, security), "
            "optional doc/Makefile checks, then commit, push, and open a pull "
            "request."
        ),
    },
    {
        "cmd": "merge",
        "order": 60,
        "argument_hint": "/flow:merge",
        "description": (
            "Merge the current branch's PR (squash), clean up the native worktree "
            "and local branch, close the linked GitHub issue, and prune stale "
            "references. Ends with the user in the main repo on main."
        ),
    },
    {
        "cmd": "deploy",
        "order": 70,
        "argument_hint": "/flow:deploy",
        "description": (
            "Run deployment via a Makefile target (default `deploy`) through the "
            "deterministic runner with a pre-deploy security gate, plus optional "
            "post-deploy health + smoke verification. Logged to .claude/deploy.log."
        ),
    },
    {
        "cmd": "cleanup",
        "order": 80,
        "argument_hint": "/flow:cleanup",
        "description": (
            "Prune stale native-worktree references, delete local branches already "
            "merged or whose remote was deleted, and prune stale remote-tracking "
            "branches. Safe to run repeatedly."
        ),
    },
    {
        "cmd": "status",
        "order": 90,
        "argument_hint": "/flow:status",
        "description": (
            "Show all active native worktrees with their linked issue, branch, "
            "dirty state, unpushed commits, and open PR status. Quick per-day "
            "glance at in-flight work."
        ),
    },
    {
        "cmd": "doctor",
        "order": 100,
        "argument_hint": "/flow:doctor",
        "description": (
            "Diagnose the claude-power-pack flow workflow environment - git/gh/uv, "
            "repo state, Makefile targets, hooks, ~/.claude scripts, the flow "
            "permission allowlist, active worktrees, GitHub integration, CI/CD "
            "readiness (lib/cicd), MCP server reachability, and repo-vs-global flow "
            "skill drift. Read-only."
        ),
    },
]

# Drift statuses
OK = "OK"
DRIFTED = "DRIFTED"
MISSING = "MISSING"
STALE_SOURCE = "STALE_SOURCE"  # source command file vanished from the repo


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _strip_leading_frontmatter(text: str) -> str:
    """Drop a leading `---\\n ... \\n---\\n` YAML block if the command has one.

    The repo commands check/cleanup/doctor carry their own frontmatter
    (description + allowed-tools); the rest start straight at `# Flow: ...`. The
    skill supplies its own frontmatter, so the command's is redundant in the body.
    """
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---\n", 4)
    if end == -1:
        return text
    return text[end + len("\n---\n") :].lstrip("\n")


def _render_skill(spec: dict, source_text: str, source_sha: str) -> str:
    name = f"flow-{spec['cmd']}"
    body = _strip_leading_frontmatter(source_text).rstrip("\n")
    lines = [
        _marker(spec["cmd"]),
        "---",
        f"name: {name}",
        f"description: {spec['description']}",
        f"argument-hint: {spec['argument_hint']}",
        "metadata:",
        f"  source: .claude/commands/flow/{spec['cmd']}.md",
        f"  source_sha256: {source_sha}",
        "  family: flow",
        f"  order: {spec['order']}",
        "---",
        "",
        body,
        "",
    ]
    return "\n".join(lines)


def _source_path(commands_dir: Path, cmd: str) -> Path:
    return commands_dir / f"{cmd}.md"


def _recorded_sha(skill_md: Path) -> str | None:
    """Return the source_sha256 recorded in an installed skill, or None."""
    try:
        for line in skill_md.read_text(encoding="utf-8", errors="replace").splitlines():
            m = re.match(r"\s*source_sha256:\s*([0-9a-f]{64})\s*$", line)
            if m:
                return m.group(1)
    except OSError:
        pass
    return None


def classify(skills_dir: Path, commands_dir: Path) -> list[dict]:
    findings: list[dict] = []
    for spec in SKILLS:
        cmd = spec["cmd"]
        name = f"flow-{cmd}"
        src = _source_path(commands_dir, cmd)
        if not src.is_file():
            findings.append({"skill": name, "status": STALE_SOURCE,
                             "detail": f"source {src} not found"})
            continue
        source_sha = _sha256(src.read_bytes())
        skill_md = skills_dir / name / "SKILL.md"
        if not skill_md.is_file():
            findings.append({"skill": name, "status": MISSING,
                             "detail": "not installed in mirror"})
            continue
        recorded = _recorded_sha(skill_md)
        if recorded == source_sha:
            findings.append({"skill": name, "status": OK, "detail": ""})
        else:
            why = "no source_sha256 recorded" if recorded is None else "source changed"
            findings.append({"skill": name, "status": DRIFTED, "detail": why})
    return findings


def drifted(findings: list[dict]) -> list[dict]:
    return [f for f in findings if f["status"] != OK]


def write_mirror(skills_dir: Path, commands_dir: Path) -> int:
    written = 0
    for spec in SKILLS:
        cmd = spec["cmd"]
        name = f"flow-{cmd}"
        src = _source_path(commands_dir, cmd)
        if not src.is_file():
            print(f"SKIP {name}: source {src} not found", file=sys.stderr)
            continue
        raw = src.read_bytes()
        content = _render_skill(spec, raw.decode("utf-8"), _sha256(raw))
        dest = skills_dir / name / "SKILL.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"WROTE {dest}")
        written += 1
    print(f"\n{written} flow skill(s) synced from {commands_dir} -> {skills_dir}")
    return 0 if written == len(SKILLS) else 1


def render_table(findings: list[dict]) -> str:
    lines = ["Flow Skill Mirror Drift", "=======================", ""]
    lines.append(f"{'Skill':<16} {'Status':<12} Detail")
    lines.append(f"{'-' * 16} {'-' * 12} {'-' * 30}")
    for f in findings:
        lines.append(f"{f['skill']:<16} {f['status']:<12} {f['detail']}")
    lines.append("")
    bad = drifted(findings)
    if bad:
        lines.append(
            f"{len(bad)} skill(s) out of sync with .claude/commands/flow/. "
            "Regenerate: python3 scripts/flow-skill-sync.py --write"
        )
    else:
        lines.append("Global flow-* mirror matches repo commands.")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        add_help=True, description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true",
                      help="Report drift table (default); exit 1 if drift found")
    mode.add_argument("--write", action="store_true",
                      help="(Re)generate the global flow-* mirror from repo commands")
    parser.add_argument("--json", action="store_true", help="Emit findings as JSON")
    parser.add_argument("--skills-dir", default=None)
    parser.add_argument("--commands-dir", default=None)
    args = parser.parse_args(argv)

    home = Path(os.path.expanduser("~"))
    skills_dir = Path(args.skills_dir) if args.skills_dir else home / ".claude" / "skills"
    commands_dir = (
        Path(args.commands_dir) if args.commands_dir
        else REPO_ROOT / ".claude" / "commands" / "flow"
    )

    if not commands_dir.is_dir():
        print(f"ERROR: commands dir not found: {commands_dir}", file=sys.stderr)
        return 2

    if args.write:
        return write_mirror(skills_dir, commands_dir)

    findings = classify(skills_dir, commands_dir)
    if args.json:
        print(json.dumps(findings, indent=2))
        return 1 if drifted(findings) else 0

    print(render_table(findings))
    return 1 if drifted(findings) else 0


if __name__ == "__main__":
    sys.exit(main())
