#!/usr/bin/env python3
"""skill-drift.py - Detect drift between CPP's deprecation list and installed skills.

Part of Claude Power Pack (CPP). Companion to scripts/drift-detect.sh, which does
the same job for MCP servers and systemd units.

The global skill surface (~/.claude/skills/) accumulates "generated" skill
directories - each SKILL.md carries a `<!-- GENERATED by claude-power-pack -->`
marker plus `metadata.family` frontmatter. CPP's manifest-driven generator was
retired, so there is no forward source-of-truth that enumerates the live skills:
EVERY generated skill references a `manifests/<family>/<name>.yaml` source that no
longer exists in the repo. A blanket "remove anything not in the repo" prune would
therefore delete live skills (flow-auto, grill-me, issue-*, ...).

So classification is driven ONLY by the curated deprecation list of record,
`.claude/deprecated-skills.yaml` (seeded by issue #394). Statuses:

  DEPRECATED - generated skill explicitly named in a deprecated family's `skills`
  ORPHANED   - generated skill whose family is a fully-retired family
               (`entire_family: true`) but is not explicitly listed (a stray
               member). Never fires for partially-deprecated families.
  OK         - any other generated skill (left untouched)
  IGNORED    - directory without the GENERATED marker (hand-authored / not ours);
               never classified for removal, never pruned

Limitation (silent drift): a skill removed from CPP without a deprecation-list
entry will show as OK and never be flagged. Maintainers must add removed skills
to .claude/deprecated-skills.yaml. This is reported in --check output.

Usage:
  skill-drift.py                       # report table; exit 1 if drift found
  skill-drift.py --check               # same as no args (explicit)
  skill-drift.py --json                # machine-readable findings (array)
  skill-drift.py --prune NAME [NAME..] # move DEPRECATED/ORPHANED skills to backup
  skill-drift.py --help

Options:
  --skills-dir DIR        Skills directory (default: ~/.claude/skills)
  --deprecated-file FILE  Deprecation list (default: <repo>/.claude/deprecated-skills.yaml)
  --backup-dir DIR        Prune backup root (default: ~/.claude/.backup/skills)
  --verbose               Also list OK / IGNORED skills in the report

Exit codes:
  0 - No drift (no DEPRECATED/ORPHANED skills), or prune succeeded
  1 - Drift detected (--check), or prune refused/failed
  2 - Usage error
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

GENERATED_MARKER = "GENERATED by claude-power-pack"

# Status constants
DEPRECATED = "DEPRECATED"
ORPHANED = "ORPHANED"
OK = "OK"
IGNORED = "IGNORED"

REPO_ROOT = Path(__file__).resolve().parents[1]


# --------------------------------------------------------------------------- #
# Deprecation-list parsing
# --------------------------------------------------------------------------- #
def _load_yaml(text: str) -> dict:
    """Load YAML, preferring PyYAML; fall back to a minimal parser if absent.

    The fallback handles exactly the deprecated-skills.yaml shape: a top-level
    `version` scalar and a `deprecated:` block list of mappings, each with
    scalar fields plus a `skills:` block list. It is intentionally small; the
    real parser (PyYAML) is present in base python3 and in dev deps.
    """
    try:
        import yaml  # type: ignore

        return yaml.safe_load(text) or {}
    except ImportError:
        return _fallback_parse(text)


def _strip_comment(value: str) -> str:
    # Remove an unquoted trailing "# comment". Good enough for this controlled file.
    in_single = in_double = False
    for i, ch in enumerate(value):
        if ch == "'" and not in_double:
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        elif ch == "#" and not in_single and not in_double:
            if i == 0 or value[i - 1] in " \t":
                return value[:i]
    return value


def _scalar(value: str) -> object:
    value = _strip_comment(value).strip()
    if not value or value in (">-", ">", "|", "|-"):
        return ""
    if (value[0] == value[-1]) and value[0] in ("'", '"') and len(value) >= 2:
        return value[1:-1]
    low = value.lower()
    if low in ("true", "false"):
        return low == "true"
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def _fallback_parse(text: str) -> dict:
    """Minimal YAML parser for the deprecated-skills.yaml schema only."""
    result: dict = {}
    families: list[dict] = []
    current: dict | None = None
    in_skills = False
    skills_indent = -1

    for raw in text.splitlines():
        line = raw.rstrip("\n")
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        body = line.lstrip(" ")

        # Top-level scalar (e.g. "version: 1")
        if indent == 0 and not body.startswith("-") and ":" in body:
            key, _, val = body.partition(":")
            key = key.strip()
            if key == "deprecated":
                result["deprecated"] = families
            else:
                result[key] = _scalar(val)
            in_skills = False
            continue

        # New family entry: "- family: wiki"
        if body.startswith("- ") and "family:" in body:
            current = {}
            families.append(current)
            in_skills = False
            after = body[2:]
            key, _, val = after.partition(":")
            current[key.strip()] = _scalar(val)
            continue

        if current is None:
            continue

        # Inside the skills block list
        if in_skills and body.startswith("- ") and indent > skills_indent:
            current.setdefault("skills", []).append(_scalar(body[2:]))
            continue
        else:
            in_skills = False

        # A field on the current family mapping
        if ":" in body and not body.startswith("- "):
            key, _, val = body.partition(":")
            key = key.strip()
            if key == "skills":
                current["skills"] = []
                in_skills = True
                skills_indent = indent
            else:
                current[key] = _scalar(val)

    if "deprecated" not in result:
        result["deprecated"] = families
    return result


def load_deprecation_index(deprecated_file: Path) -> tuple[dict, dict]:
    """Return (by_skill, by_family).

    by_skill[name]  -> family dict (skill explicitly listed -> DEPRECATED)
    by_family[fam]  -> family dict ONLY when entire_family is true (-> ORPHANED gate)
    """
    by_skill: dict[str, dict] = {}
    by_family: dict[str, dict] = {}
    if not deprecated_file.is_file():
        return by_skill, by_family

    data = _load_yaml(deprecated_file.read_text(encoding="utf-8"))
    for fam in data.get("deprecated") or []:
        if not isinstance(fam, dict):
            continue
        meta = {
            "family": fam.get("family", ""),
            "reason": (fam.get("reason") or "").strip(),
            "replacement": (fam.get("replacement") or "").strip(),
        }
        for name in fam.get("skills") or []:
            by_skill[str(name)] = meta
        if fam.get("entire_family") is True and fam.get("family"):
            by_family[str(fam["family"])] = meta
    return by_skill, by_family


# --------------------------------------------------------------------------- #
# Skill enumeration + classification
# --------------------------------------------------------------------------- #
def read_family(skill_md: Path) -> str:
    """Extract metadata.family from a SKILL.md, or '' if absent."""
    try:
        for line in skill_md.read_text(encoding="utf-8", errors="replace").splitlines():
            m = re.match(r"\s*family:\s*(\S+)", line)
            if m:
                return m.group(1).strip("'\"")
    except OSError:
        pass
    return ""


def is_generated(skill_md: Path) -> bool:
    try:
        return GENERATED_MARKER in skill_md.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def classify(skills_dir: Path, deprecated_file: Path) -> list[dict]:
    """Classify every directory under skills_dir. Returns sorted findings."""
    by_skill, by_family = load_deprecation_index(deprecated_file)
    findings: list[dict] = []

    if not skills_dir.is_dir():
        return findings

    for entry in sorted(skills_dir.iterdir(), key=lambda p: p.name):
        if not entry.is_dir():
            continue
        name = entry.name
        skill_md = entry / "SKILL.md"

        if not skill_md.is_file() or not is_generated(skill_md):
            findings.append(
                {"skill": name, "family": "", "status": IGNORED,
                 "reason": "not a CPP-generated skill", "replacement": ""}
            )
            continue

        family = read_family(skill_md)
        if name in by_skill:
            meta = by_skill[name]
            findings.append(
                {"skill": name, "family": family or meta["family"], "status": DEPRECATED,
                 "reason": meta["reason"], "replacement": meta["replacement"]}
            )
        elif family and family in by_family:
            meta = by_family[family]
            findings.append(
                {"skill": name, "family": family, "status": ORPHANED,
                 "reason": f"stray member of fully-retired family '{family}': {meta['reason']}",
                 "replacement": meta["replacement"]}
            )
        else:
            findings.append(
                {"skill": name, "family": family, "status": OK, "reason": "", "replacement": ""}
            )
    return findings


def removable(findings: list[dict]) -> list[dict]:
    return [f for f in findings if f["status"] in (DEPRECATED, ORPHANED)]


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #
def render_table(findings: list[dict], verbose: bool) -> str:
    lines = ["Skill Drift Report", "==================", ""]
    shown = [f for f in findings if verbose or f["status"] in (DEPRECATED, ORPHANED)]
    if shown:
        lines.append(f"{'Skill':<24} {'Family':<12} {'Status'}")
        lines.append(f"{'-' * 24} {'-' * 12} {'-' * 10}")
        for f in shown:
            lines.append(f"{f['skill']:<24} {f['family'] or '-':<12} {f['status']}")
        lines.append("")

    counts = {OK: 0, DEPRECATED: 0, ORPHANED: 0, IGNORED: 0}
    for f in findings:
        counts[f["status"]] = counts.get(f["status"], 0) + 1
    lines.append(
        "Summary: "
        f"{counts[OK]} OK, {counts[DEPRECATED]} deprecated, "
        f"{counts[ORPHANED]} orphaned, {counts[IGNORED]} ignored (hand-authored)"
    )

    drift = counts[DEPRECATED] + counts[ORPHANED]
    if drift == 0:
        lines.append("No deprecated or orphaned skills installed.")
    else:
        lines.append(
            f"{drift} skill(s) flagged for removal. They are generated artifacts, "
            "not user content; removal is offered with confirmation by /cpp:update."
        )
    lines.append(
        "Note: detection is curated-list driven (.claude/deprecated-skills.yaml). "
        "Skills removed from CPP without a deprecation entry are not auto-detected."
    )
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Prune (guarded move-to-backup)
# --------------------------------------------------------------------------- #
def prune(names: list[str], skills_dir: Path, backup_dir: Path,
          findings: list[dict]) -> int:
    status_by_name = {f["skill"]: f["status"] for f in findings}
    skills_root = skills_dir.resolve()
    refused = 0
    moved = 0
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    dest_root = backup_dir / stamp

    for name in names:
        # Path-traversal guard: simple name, direct child only.
        if "/" in name or "\\" in name or name in ("", ".", "..") or ".." in name:
            print(f"REFUSED {name}: invalid skill name", file=sys.stderr)
            refused += 1
            continue
        entry_path = skills_dir / name
        # Refuse symlinks BEFORE resolving: a symlink to a sibling would otherwise
        # pass the direct-child check and move the link's real target (data loss).
        if entry_path.is_symlink():
            print(f"REFUSED {name}: symlinked entry", file=sys.stderr)
            refused += 1
            continue
        target = entry_path.resolve()
        if target.parent != skills_root:
            print(f"REFUSED {name}: not a direct child of {skills_dir}", file=sys.stderr)
            refused += 1
            continue

        status = status_by_name.get(name)
        if status not in (DEPRECATED, ORPHANED):
            label = status or "not installed"
            print(f"REFUSED {name}: classified {label}; only DEPRECATED/ORPHANED "
                  "skills may be pruned", file=sys.stderr)
            refused += 1
            continue
        if not target.is_dir():
            print(f"REFUSED {name}: directory not found", file=sys.stderr)
            refused += 1
            continue

        dest = dest_root / name
        if dest.exists():  # defensive: never merge into a pre-existing backup dir
            dest = dest_root / f"{name}.{moved}"
        dest_root.mkdir(parents=True, exist_ok=True)
        shutil.move(str(target), str(dest))
        print(f"PRUNED {name} -> {dest}")
        moved += 1

    if refused:
        print(f"\n{moved} pruned, {refused} refused.", file=sys.stderr)
        return 1
    print(f"\n{moved} skill(s) pruned. Backup: {dest_root}")
    return 0


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(add_help=True, description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="Report drift table (default); exit 1 if drift found")
    parser.add_argument("--json", action="store_true", help="Emit findings as JSON array")
    parser.add_argument("--prune", nargs="+", metavar="NAME",
                        help="Move named DEPRECATED/ORPHANED skills to backup")
    parser.add_argument("--verbose", action="store_true", help="List OK/IGNORED too")
    parser.add_argument("--skills-dir", default=None)
    parser.add_argument("--deprecated-file", default=None)
    parser.add_argument("--backup-dir", default=None)
    args = parser.parse_args(argv)

    home = Path(os.path.expanduser("~"))
    skills_dir = Path(args.skills_dir) if args.skills_dir else home / ".claude" / "skills"
    deprecated_file = (
        Path(args.deprecated_file) if args.deprecated_file
        else REPO_ROOT / ".claude" / "deprecated-skills.yaml"
    )
    backup_dir = (
        Path(args.backup_dir) if args.backup_dir
        else home / ".claude" / ".backup" / "skills"
    )

    findings = classify(skills_dir, deprecated_file)

    if args.prune:
        return prune(args.prune, skills_dir, backup_dir, findings)

    if args.json:
        print(json.dumps(findings, indent=2))
        return 1 if removable(findings) else 0

    # default / --check
    print(render_table(findings, verbose=args.verbose))
    return 1 if removable(findings) else 0


if __name__ == "__main__":
    sys.exit(main())
